"use client";

import { useEffect, useRef, useState, type ReactNode } from "react";
import { createPortal } from "react-dom";
import { useLanguage } from "../language";
import { isMockOtp } from "./mock-login-data";
import { Icon, type IconName } from "./Icon";
import { readBrowserStore, writeBrowserStore } from "./browser-store";
import type { ClaimRecord } from "./claims-data";
import styles from "./account-profile.module.css";

type Flow = "identity" | "kyc" | "nomination" | "joint";
type Request = { title: string; status: string; route: string };
type ProfileSection = { id: Flow; title: string; icon: IconName; fields: [string, string][] };

const sections: ProfileSection[] = [
  { id: "identity", title: "Identity and contact", icon: "user", fields: [["Name", "Rahul Patil"], ["Universal Account Number", "1009 2000 0123"], ["Aadhaar", "•••• •••• 5478 · Verified by UIDAI"], ["PAN", "AXXPP1234K · Verified"], ["Date of birth", "14 May 1992"], ["Gender", "Male"], ["Father's name", "Madhav Patil"], ["Marital status", "Married"], ["Mobile number", "+91 98••• 8842 · Verified"], ["Email ID", "rahul.patil@example.com · Verified"], ["Correspondence address", "A-402, Green Meadows, Whitefield, Bengaluru, Karnataka 560066"], ["Permanent address", "12 Shastri Nagar, Pune, Maharashtra 411005"]] },
  { id: "kyc", title: "KYC and bank", icon: "shield", fields: [["Aadhaar", "•••• •••• 5478 · Verified by UIDAI"], ["PAN", "AXXPP1234K · Digitally approved"], ["Bank account", "HDFC Bank •••• 4821 · Verified"], ["IFSC", "HDFC0001234"]] },
  { id: "nomination", title: "Nomination", icon: "users", fields: [["Nominee", "Priya Patil"], ["Relationship", "Spouse"], ["Date of birth", "18 Sep 1994"], ["EPF share", "100%"], ["e-Nomination status", "Registered"]] },
  { id: "joint", title: "Employment", icon: "briefcase", fields: [["Current establishment", "Infosys Limited"], ["Member ID", "MHBAN1318576000010404"], ["Date of joining", "03 Nov 2025"], ["PF transfer status", "Previous PF transferred"], ["Previous employment", "Techcore Systems · 01 Nov 2022 – 07 Aug 2023"]] },
];
const selfAttested = new Set(["Mobile number", "Email ID", "Correspondence address", "Permanent address"]);

export function AccountProfile({ initialSection, onTrackRequest, onLogout }: { initialSection?: string; onTrackRequest: (id: string) => void; onLogout?: () => void }) {
  const { t } = useLanguage(); const [flow, setFlow] = useState<Flow | null>(null); const [request, setRequest] = useState<Request | null>(() => readBrowserStore<Request | null>("epfo.profile-request", null));
  useEffect(() => { if (initialSection) document.getElementById(initialSection)?.scrollIntoView({ block: "start" }); }, [initialSection]);
  useEffect(() => writeBrowserStore("epfo.profile-request", request), [request]);
  const submitRequest = (next: Request) => {
    const id = `SRV-${crypto.randomUUID()}`;
    const tracker: ClaimRecord = { id, type: next.title, amount: "—", submitted: "28 Aug 2026", status: "Submitted", message: `${next.status}. Your request is being processed.`, steps: ["Submitted", "Verification", "EPFO decision"], currentStep: 0, form: next.route };
    const current = readBrowserStore<ClaimRecord[]>("epfo.service-requests", []);
    writeBrowserStore("epfo.service-requests", [tracker, ...current]);
    setRequest(next);
    onTrackRequest(id);
  };
  return <section className={styles.profile} aria-label={t("Profile details")}>
    <article className={styles.identity}><span><Icon name="user" size={22} /></span><div><p className="eyebrow">MEMBER PROFILE</p><h2>Rahul Patil</h2><p>Aadhaar verified · UAN 1009 2000 0123</p></div>{onLogout && <button className="profile-logout" type="button" onClick={onLogout}>Log out</button>}</article>
    <section className={styles.requests}><div><p className="eyebrow">PROFILE REQUESTS</p><h2>{request ? "1 request in progress" : "No profile requests in progress"}</h2><p>{request ? `${request.title} · ${request.status}` : "Request a correction from the relevant profile section."}</p></div>{request && <span>{request.route}</span>}</section>
    {sections.map((section) => <section id={section.id} key={section.id} className={`${styles.section} ${initialSection === section.id ? styles.highlighted : ""}`}><header><div className={styles.sectionTitle}><span><Icon name={section.icon} size={17} /></span><h2>{t(section.title)}</h2></div><button type="button" onClick={() => setFlow(section.id)}>Request update <Icon name="arrow" size={14} /></button></header><dl>{section.fields.map(([label, value]) => <div key={label}><dt>{t(label)}</dt><dd>{value}</dd></div>)}</dl></section>)}
    {flow && <ProfileFlow flow={flow} onClose={() => setFlow(null)} onRequest={submitRequest} />}
    <p className={styles.note}><Icon name="shield" size={16} />Profile updates use Aadhaar verification first. Review is used only when it cannot confirm the change.</p>
  </section>;
}

function Shell({ title, onClose, resetKey, children }: { title: string; onClose: () => void; resetKey?: number | string; children: ReactNode }) {
  const drawerRef = useRef<HTMLElement>(null);
  useEffect(() => {
    // Lock background scroll while the drawer is open — on mobile the drawer covers the full screen, so a scrollable background behind it is what leaves the member feeling stuck.
    const previous = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => { document.body.style.overflow = previous; };
  }, []);
  useEffect(() => {
    // Each step (form -> OTP -> loading -> done) renders in the same scrollable drawer without remounting it, so without this the drawer keeps whatever scroll position the member was at when they submitted the previous step.
    drawerRef.current?.scrollTo({ top: 0 });
  }, [resetKey]);
  useEffect(() => {
    const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);
  // Portalled to document.body: `.content` carries the page-enter animation, which leaves a permanent transform (fill:both) that turns it into a containing block for fixed descendants — without this, the drawer renders inside that box instead of over the full viewport, landing it behind the fixed topbar.
  return createPortal(
    <div className={styles.drawerLayer}><button className={styles.scrim} type="button" aria-label="Close update request" onClick={onClose} /><aside ref={drawerRef} className={styles.drawer} role="dialog" aria-modal="true"><header><div><p className="eyebrow">UPDATE REQUEST</p><h2>{title}</h2><p>Prototype only. No information is sent to Aadhaar, your employer, or EPFO.</p></div><button type="button" onClick={onClose} aria-label="Close update request"><Icon name="close" /></button></header>{children}</aside></div>,
    document.body,
  );
}
function Otp({ onDone }: { onDone: () => void }) { const [otp, setOtp] = useState(""); const [error, setError] = useState(false); const [method, setMethod] = useState<"choose" | "otp" | "face">("choose"); if (method === "face") return <FaceVerification onDone={onDone} onUseOtp={() => setMethod("otp")} />; if (method === "choose") return <section className={styles.form}><section className={styles.auth}><Icon name="shield" size={19} /><div><strong>Continue with UMANG</strong><p>Choose Aadhaar OTP or Face Authentication. You will return here after verification.</p></div></section><button className="primary-button" type="button" onClick={() => setMethod("face")}>Use Face Authentication</button><button className="primary-button" type="button" onClick={() => setMethod("otp")}>Use Aadhaar OTP instead</button></section>; return <form className={styles.form} onSubmit={(e) => { e.preventDefault(); if (!isMockOtp(otp)) return setError(true); onDone(); }}><section className={styles.auth}><Icon name="shield" size={19} /><div><strong>UMANG · Aadhaar OTP</strong><p>UMANG requested an OTP for your Aadhaar-linked mobile number.</p></div></section><label>6-digit Aadhaar OTP<input required autoFocus inputMode="numeric" maxLength={6} value={otp} onChange={(e) => { setOtp(e.target.value); setError(false); }} placeholder="123456" /></label><small className={styles.mockOtp}>Mock OTP: 123456</small>{error && <small className={styles.error}>Enter the mock OTP shown above.</small>}<button className="primary-button">Return verified to EPFO</button></form>; }
function FaceVerification({ onDone, onUseOtp }: { onDone: () => void; onUseOtp: () => void }) { const video = useRef<HTMLVideoElement>(null); const stream = useRef<MediaStream | null>(null); const [status, setStatus] = useState<"requesting" | "ready" | "verifying" | "error">("requesting"); const unsupported = typeof navigator !== "undefined" && !navigator.mediaDevices?.getUserMedia; useEffect(() => { let active = true; if (unsupported) return; navigator.mediaDevices.getUserMedia({ video: { facingMode: "user" }, audio: false }).then((next) => { if (!active) return next.getTracks().forEach((track) => track.stop()); stream.current = next; if (video.current) video.current.srcObject = next; setStatus("ready"); }).catch(() => active && setStatus("error")); return () => { active = false; stream.current?.getTracks().forEach((track) => track.stop()); }; }, [unsupported]); if (!unsupported && (status === "requesting" || status === "verifying")) return <Loader title={status === "requesting" ? "Requesting camera access" : "Confirming live photo"} detail="Your camera preview stays on this device." />; return <section className={styles.form}><section className={styles.auth}><Icon name="user" size={19} /><div><strong>UMANG · Aadhaar Face Authentication</strong><p>Confirm a live photo in your camera. This prototype does not upload or retain it.</p></div></section>{status === "ready" ? <video ref={video} autoPlay muted playsInline aria-label="Live camera preview" style={{ width: "100%", aspectRatio: "3 / 4", objectFit: "cover", borderRadius: 12, background: "#111" }} /> : <small className={styles.error}>Camera access was not granted or is unavailable.</small>}{status === "ready" && <button className="primary-button" type="button" onClick={() => { setStatus("verifying"); window.setTimeout(onDone, 850); }}>Verify live photo</button>}<button className="primary-button" type="button" onClick={onUseOtp}>Use Aadhaar OTP instead</button></section>; }
function Loader({ title, detail }: { title: string; detail: string }) { return <div className={styles.loader}><span /><strong>{title}</strong><p>{detail}</p></div>; }
function Done({ title, detail, onClose }: { title: string; detail: string; onClose: () => void }) { return <div className={styles.complete}><span><Icon name="shield" size={22} /></span><h3>{title}</h3><p>{detail}</p><button className="primary-button" onClick={onClose}>Done</button></div>; }

function ProfileFlow({ flow, onClose, onRequest }: { flow: Flow; onClose: () => void; onRequest: (r: Request) => void }) {
  if (flow === "kyc") return <Kyc onClose={onClose} onRequest={onRequest} />;
  if (flow === "nomination") return <Nomination onClose={onClose} onRequest={onRequest} />;
  if (flow === "joint") return <Joint onClose={onClose} onRequest={onRequest} />;
  return <Identity onClose={onClose} onRequest={onRequest} />;
}
function Kyc({ onClose, onRequest }: { onClose: () => void; onRequest: (r: Request) => void }) { const [stage, setStage] = useState(0); const [kind, setKind] = useState("Bank account"); useEffect(() => { if (stage === 2) { const id = setTimeout(() => { onRequest({ title: `${kind} update`, status: "Awaiting employer approval", route: "Self-attested" }); setStage(3); }, 900); return () => clearTimeout(id); } }, [stage, kind, onRequest]); return <Shell title="KYC and bank" onClose={onClose} resetKey={stage}>{stage === 0 ? <form className={styles.form} onSubmit={(e) => { e.preventDefault(); setStage(1); }}><label>KYC detail<select value={kind} onChange={(e) => setKind(e.target.value)}><option>PAN</option><option>Bank account</option></select></label>{kind === "PAN" ? <label>PAN number<input required defaultValue="AXXPP1234K" /></label> : <><label>Bank account number<input required defaultValue="50200076543210" /></label><label>IFSC code<input required defaultValue="HDFC0001234" /></label></>}<Route title="Self-attested" detail="Aadhaar authentication starts your request. Your employer approves the seeded KYC record." /><button className="primary-button">Continue to Aadhaar authentication</button></form> : stage === 1 ? <Otp onDone={() => setStage(2)} /> : stage === 2 ? <Loader title="Verifying your KYC request" detail="Aadhaar authentication is complete. Preparing employer verification." /> : <Done title="KYC request submitted" detail={`${kind} is awaiting employer approval.`} onClose={onClose} />}</Shell>; }
function Nomination({ onClose, onRequest }: { onClose: () => void; onRequest: (r: Request) => void }) { const [stage, setStage] = useState(0); useEffect(() => { if (stage === 2) { const id = setTimeout(() => { onRequest({ title: "e-Nomination", status: "Registered", route: "Self-attested" }); setStage(3); }, 900); return () => clearTimeout(id); } }, [stage, onRequest]); return <Shell title="e-Nomination" onClose={onClose} resetKey={stage}>{stage === 0 ? <form className={styles.form} onSubmit={(e) => { e.preventDefault(); setStage(1); }}><label>Nominee name<input required defaultValue="Priya Patil" /></label><label>Relationship<select defaultValue="Spouse"><option>Spouse</option><option>Child</option><option>Parent</option></select></label><label>EPF share (%)<input required type="number" min="1" max="100" defaultValue="100" /></label><Route title="Self-attested e-Sign" detail="Use Aadhaar-linked OTP to e-Sign this nomination." /><button className="primary-button">Continue to e-Sign</button></form> : stage === 1 ? <Otp onDone={() => setStage(2)} /> : stage === 2 ? <Loader title="Registering e-Nomination" detail="Your e-Sign is being recorded." /> : <Done title="e-Nomination registered" detail="Your nomination is registered for this prototype session." onClose={onClose} />}</Shell>; }
function Identity({ onClose, onRequest }: { onClose: () => void; onRequest: (r: Request) => void }) { const [stage, setStage] = useState(0); const [detail, setDetail] = useState("Name"); useEffect(() => { if (stage === 2) { const id = setTimeout(() => { if (selfAttested.has(detail)) { onRequest({ title: `${detail} update`, status: "Verified", route: "Self-attested" }); setStage(3); } else setStage(4); }, 900); return () => clearTimeout(id); } }, [stage, detail, onRequest]); if (stage === 4) return <Joint onClose={onClose} onRequest={onRequest} initialDetail={detail} />; return <Shell title="Identity and contact" onClose={onClose} resetKey={stage}>{stage === 0 ? <form className={styles.form} onSubmit={(e) => { e.preventDefault(); setStage(1); }}><label>Detail to update<select value={detail} onChange={(e) => setDetail(e.target.value)}>{sections[0].fields.filter(([x]) => !["Universal Account Number", "Aadhaar", "PAN"].includes(x)).map(([x]) => <option key={x}>{x}</option>)}</select></label><label>Correct value<input required /></label><button className="primary-button">Continue to Aadhaar authentication</button></form> : stage === 1 ? <Otp onDone={() => setStage(2)} /> : stage === 2 ? <Loader title="Checking Aadhaar details" detail="We are confirming whether this update matches Aadhaar." /> : <Done title="Profile update verified" detail="Your self-attested contact update has been accepted." onClose={onClose} />}</Shell>; }
function Joint({ onClose, onRequest, initialDetail = "Date of joining" }: { onClose: () => void; onRequest: (r: Request) => void; initialDetail?: string }) { const [stage, setStage] = useState(0); const [detail, setDetail] = useState(initialDetail); useEffect(() => { if (stage === 2) { onRequest({ title: `${detail} correction`, status: "Employer review in progress", route: "Joint Declaration" }); const id = setTimeout(() => setStage(3), 900); return () => clearTimeout(id); } if (stage === 3) { const id = setTimeout(() => setStage(4), 900); return () => clearTimeout(id); } }, [stage, detail, onRequest]); return <Shell title="Joint Declaration" onClose={onClose} resetKey={stage}>{stage === 0 ? <form className={styles.form} onSubmit={(e) => { e.preventDefault(); setStage(1); }}><section className={styles.current}><strong>Member ID</strong><span>MHBAN1318576000010404 · Infosys Limited</span></section><label>Correction requested<select value={detail} onChange={(e) => setDetail(e.target.value)}>{["Name", "Date of birth", "Gender", "Father's name", "Marital status", "Date of joining", "Date of exit", "Reason for exit"].map((x) => <option key={x}>{x}</option>)}</select></label><label>Current EPFO record<input disabled value={detail === "Date of joining" ? "03 Nov 2025" : "Recorded value"} /></label><label>Correct value<input required /></label><label>Supporting document<input required type="file" accept=".pdf,.jpg,.jpeg,.png" /></label><small className={styles.help}>Upload one prescribed supporting document. Files remain only in this mock browser session.</small><button className="primary-button">Authenticate and submit declaration</button></form> : stage === 1 ? <Otp onDone={() => setStage(2)} /> : stage === 2 ? <Review current={1} detail="Your employer is reviewing this Joint Declaration." /> : stage === 3 ? <Review current={2} detail="Employer review is complete. EPFO is reviewing your document." /> : <Done title="Joint Declaration submitted" detail="The simulated EPFO review is complete." onClose={onClose} />}</Shell>; }
function Route({ title, detail }: { title: string; detail: string }) { return <section className={styles.route}><span><Icon name="shield" size={18} /></span><div><strong>{title}</strong><p>{detail}</p></div></section>; }
function Review({ current, detail }: { current: number; detail: string }) { const steps = ["Submitted", "Employer review", "EPFO decision"]; return <div className={styles.timeline}><Loader title={steps[current]} detail={detail} /><ol>{steps.map((x, i) => <li className={i <= current ? styles.current : ""} key={x}>{x}</li>)}</ol></div>; }
