"use client";

import { createContext, useCallback, useContext, useSyncExternalStore, type ReactNode } from "react";

export const languages = [
  { id: "en", label: "English" }, { id: "hi", label: "Hinglish" }, { id: "bn", label: "Banglish" }, { id: "mr", label: "Marathinglish" }, { id: "te", label: "Teluglish" }, { id: "ta", label: "Tanglish" }, { id: "gu", label: "Gujlish" }, { id: "kn", label: "Kanglish" }, { id: "ml", label: "Manglish" }, { id: "pa", label: "Punglish" }, { id: "or", label: "Odia (Roman)" },
] as const;
export type Lang = (typeof languages)[number]["id"];

const dict: Record<string, { en: string; hi: string }> = {
  "MINISTRY OF LABOUR & EMPLOYMENT": { en: "MINISTRY OF LABOUR & EMPLOYMENT", hi: "SHRAM AUR ROZGAR MANTRALAYA" },
  "Social Security, Peace of Mind": { en: "Social Security, Peace of Mind", hi: "Samajik suraksha, mann ki shanti." },
  "Your work history, savings and protection—connected through one account.": { en: "Your work history, savings and protection—connected through one account.", hi: "Aapki kaam ki history, bachat aur suraksha—ek account se judi hui." },
  "A calmer way to manage your provident fund.": { en: "A calmer way to manage your provident fund.", hi: "Apne provident fund ko sambhalne ka aasaan tareeka." },
  "Open navigation": { en: "Open navigation", hi: "Navigation kholen" },
  "Employees' Provident Fund Organisation": { en: "Employees' Provident Fund Organisation", hi: "कर्मचारी भविष्य निधि संगठन" },
  "SECURE ACCESS": { en: "SECURE ACCESS", hi: "सुरक्षित प्रवेश" },
  "Sign in to EPFO": { en: "Sign in to EPFO", hi: "EPFO में साइन इन करें" },
  Login: { en: "Login", hi: "लॉग इन करें" },
  "Forgot password": { en: "Forgot password", hi: "पासवर्ड भूल गए" },
  "Forgot ID": { en: "Forgot ID", hi: "ID भूल गए" },
  "Back to sign in": { en: "Back to sign in", hi: "साइन इन पर वापस जाएं" },
  "ACCOUNT RECOVERY": { en: "ACCOUNT RECOVERY", hi: "अकाउंट रिकवरी" },
  "Reset your password": { en: "Reset your password", hi: "अपना पासवर्ड रीसेट करें" },
  "Know your UAN": { en: "Know your UAN", hi: "अपना UAN जानें" },
  "Recover your login ID": { en: "Recover your login ID", hi: "अपना लॉगिन ID प्राप्त करें" },
  "We will verify your registered mobile number before continuing.": { en: "We will verify your registered mobile number before continuing.", hi: "आगे बढ़ने से पहले हम आपके पंजीकृत मोबाइल नंबर की पुष्टि करेंगे।" },
  "Find your UAN using details recorded with EPFO.": { en: "Find your UAN using details recorded with EPFO.", hi: "EPFO में दर्ज जानकारी से अपना UAN खोजें।" },
  "We will send your login ID to your registered mobile number.": { en: "We will send your login ID to your registered mobile number.", hi: "हम आपका लॉगिन ID आपके पंजीकृत मोबाइल नंबर पर भेजेंगे।" },
  "Identify using": { en: "Identify using", hi: "इनके माध्यम से पहचानें" },
  "Full name": { en: "Full name", hi: "पूरा नाम" },
  "Registered mobile number": { en: "Registered mobile number", hi: "पंजीकृत मोबाइल नंबर" },
  "Send authorisation PIN": { en: "Send authorisation PIN", hi: "ऑथराइजेशन PIN भेजें" },
  "An authorisation PIN was sent to your registered mobile number.": { en: "An authorisation PIN was sent to your registered mobile number.", hi: "आपके पंजीकृत मोबाइल नंबर पर एक ऑथराइजेशन PIN भेजा गया है।" },
  "Authorisation PIN": { en: "Authorisation PIN", hi: "ऑथराइजेशन PIN" },
  "Verify PIN": { en: "Verify PIN", hi: "PIN सत्यापित करें" },
  "Choose a new password for your account.": { en: "Choose a new password for your account.", hi: "अपने अकाउंट के लिए नया पासवर्ड चुनें।" },
  "New password": { en: "New password", hi: "नया पासवर्ड" },
  "Confirm new password": { en: "Confirm new password", hi: "नए पासवर्ड की पुष्टि करें" },
  "Reset password": { en: "Reset password", hi: "पासवर्ड रीसेट करें" },
  "Password reset": { en: "Password reset", hi: "पासवर्ड रीसेट हुआ" },
  "Your password has been updated. You can now sign in.": { en: "Your password has been updated. You can now sign in.", hi: "आपका पासवर्ड अपडेट हो गया है। अब आप साइन इन कर सकते हैं।" },
  "Your UAN has been sent": { en: "Your UAN has been sent", hi: "आपका UAN भेज दिया गया है" },
  "Your UAN was sent to your registered mobile number.": { en: "Your UAN was sent to your registered mobile number.", hi: "आपका UAN आपके पंजीकृत मोबाइल नंबर पर भेज दिया गया है।" },
  "Your login ID was sent to your registered mobile number.": { en: "Your login ID was sent to your registered mobile number.", hi: "आपका लॉगिन ID आपके पंजीकृत मोबाइल नंबर पर भेज दिया गया है।" },
  "Return to sign in": { en: "Return to sign in", hi: "साइन इन पर लौटें" },
  "Checking your details": { en: "Checking your details", hi: "आपकी जानकारी जांची जा रही है" },
  "This is a secure mock recovery flow.": { en: "This is a secure mock recovery flow.", hi: "यह एक सुरक्षित मॉक रिकवरी फ्लो है।" },
  "Choose your account type to continue.": { en: "Choose your account type to continue.", hi: "जारी रखने के लिए अपना अकाउंट प्रकार चुनें।" },
  "Account type": { en: "Account type", hi: "अकाउंट प्रकार" },
  "Member": { en: "Member", hi: "सदस्य" },
  "Establishment": { en: "Establishment", hi: "Establishment" },
  "Principal employer": { en: "Principal employer", hi: "Principal employer" },
  "Use your UAN to manage your PF account.": { en: "Use your UAN to manage your PF account.", hi: "अपना PF अकाउंट मैनेज करने के लिए UAN इस्तेमाल करें।" },
  "For authorised establishment representatives.": { en: "For authorised establishment representatives.", hi: "अधिकृत प्रतिष्ठान प्रतिनिधियों के लिए।" },
  "Track contractor and contract-worker compliance.": { en: "Track contractor and contract-worker compliance.", hi: "ठेकेदार और संविदा कर्मी अनुपालन को ट्रैक करें।" },
  "Establishment ID (PF Code)": { en: "Establishment ID (PF Code)", hi: "प्रतिष्ठान ID (PF कोड)" },
  "PF Code / registered ID": { en: "PF Code / registered ID", hi: "PF कोड / पंजीकृत ID" },
  Password: { en: "Password", hi: "पासवर्ड" },
  "A one-time password was sent to your registered mobile number.": { en: "A one-time password was sent to your registered mobile number.", hi: "आपके पंजीकृत मोबाइल नंबर पर एक OTP भेजा गया है।" },
  "Prototype sign-in: any 6-digit code is accepted.": { en: "Prototype sign-in: any 6-digit code is accepted.", hi: "Prototype sign-in: koi bhi 6-digit code accept hoga." },
  "Enter a 6-digit code to continue.": { en: "Enter a 6-digit code to continue.", hi: "Aage badhne ke liye 6-digit code daalein." },
  "Verify and sign in": { en: "Verify and sign in", hi: "सत्यापित करें और साइन इन करें" },
  "Use a different account": { en: "Use a different account", hi: "दूसरा अकाउंट इस्तेमाल करें" },
  "Verifying your details": { en: "Verifying your details", hi: "आपकी जानकारी सत्यापित की जा रही है" },
  "This is a secure mock sign-in.": { en: "This is a secure mock sign-in.", hi: "यह एक सुरक्षित मॉक साइन-इन है।" },
  "Prototype only. Do not enter real credentials.": { en: "Prototype only. Do not enter real credentials.", hi: "केवल प्रोटोटाइप। वास्तविक क्रेडेंशियल न डालें।" },
  "Mock workspace": { en: "Mock workspace", hi: "Mock workspace" },
  "EMPLOYER PORTAL": { en: "EMPLOYER PORTAL", hi: "EMPLOYER PORTAL" },
  "Welcome back": { en: "Welcome back", hi: "Wapsi par swagat hai" },
  "Authorised access": { en: "Authorised access", hi: "Adhikrit pravesh" },
  "This mock workspace is ready for your next step.": { en: "This mock workspace is ready for your next step.", hi: "यह मॉक वर्कस्पेस आपके अगले कदम के लिए तैयार है।" },
  "Close navigation": { en: "Close navigation", hi: "Navigation band karein" },
  "Main navigation": { en: "Main navigation", hi: "Main navigation" },
  Close: { en: "Close", hi: "Band karein" },
  Contribution: { en: "Contribution", hi: "Contribution" },
  "Search EPFO services": { en: "Search EPFO services", hi: "EPFO services khojiye" },
  "Search services": { en: "Search services", hi: "Services khojiye" },
  Notifications: { en: "Notifications", hi: "Notifications" },
  "Verified account": { en: "Verified account", hi: "Verified account" },
  "Currently acting as": { en: "Currently acting as", hi: "Abhi aap acting as" },
  "Need help?": { en: "Need help?", hi: "Madad chahiye?" },
  "Guides and support": { en: "Guides and support", hi: "Guides aur support" },
  "Acting as": { en: "Acting as", hi: "Abhi aap acting as" },
  "MONDAY, 24 AUGUST": { en: "MONDAY, 24 AUGUST", hi: "SOMVAAR, 24 AUGUST" },
  "Good afternoon, Rahul": { en: "Good afternoon, Rahul", hi: "Shubh dopahar, Rahul" },
  "Here’s a clear view of your provident fund.": { en: "Here’s a clear view of your provident fund.", hi: "Yahan aapka provident fund saaf-saaf dikh raha hai." },
  "Here’s what needs attention at {name}.": { en: "Here’s what needs attention at {name}.", hi: "{name} pe aapka dhyan chahiye." },
  "Download statement": { en: "Download statement", hi: "Statement download karein" },
  "Download report": { en: "Download report", hi: "Report download karein" },
  "Return to overview": { en: "Return to overview", hi: "Overview pe wapas jayein" },
  "This workspace is ready for the {item} journey. Your active role and scope remain visible while you work.": { en: "This workspace is ready for the {item} journey. Your active role and scope remain visible while you work.", hi: "{item} ke kaam ke liye ye workspace taiyaar hai. Aapka active role aur scope dikhta rahega." },
  "Switch context": { en: "Switch context", hi: "Context badlein" },
  "Choose who you want to act as. You won’t need to sign in again.": { en: "Choose who you want to act as. You won’t need to sign in again.", hi: "Chuniye ki aap kiske roop mein kaam karna chahte hain. Dubara sign-in nahi karna padega." },
  Current: { en: "Current", hi: "Current" },
  "Sensitive actions may require an OTP or e-Sign confirmation.": { en: "Sensitive actions may require an OTP or e-Sign confirmation.", hi: "Kuch kaam karne ke liye OTP ya e-Sign confirmation zaroori ho sakta hai." },
  "My PF": { en: "My PF", hi: "Mera PF" },
  "My retirement account": { en: "My retirement account", hi: "Mera retirement account" },
  "Your retirement account": { en: "Your retirement account", hi: "Aapka retirement account" },
  Personal: { en: "Personal", hi: "Personal" },
  "Personal account": { en: "Personal account", hi: "Personal account" },
  "All extensions": { en: "All extensions", hi: "Saari extensions" },
  "Authorized Signatory": { en: "Authorized Signatory", hi: "Authorized Signatory" },
  Overview: { en: "Overview", hi: "Overview" },
  Home: { en: "Home", hi: "Home" },
  Passbook: { en: "Passbook", hi: "Passbook" },
  Employment: { en: "Employment", hi: "Naukri" },
  "Service history": { en: "Service history", hi: "Seva itihaas" },
  "View this member's passbook": { en: "View this member's passbook", hi: "Is member ki passbook dekhein" },
  "SERVICE HISTORY": { en: "SERVICE HISTORY", hi: "SEVA ITIHAAS" },
  Services: { en: "Services", hi: "Services" },
  Claims: { en: "Claims", hi: "Claim" },
  "Start a claim": { en: "Start a claim", hi: "Claim shuru karein" },
  "Claim status": { en: "Claim status", hi: "Claim ka status" },
  "Past claims": { en: "Past claims", hi: "Purane claims" },
  "Your claims": { en: "Your claims", hi: "Aapke claims" },
  "Your requests": { en: "Your requests", hi: "Aapke requests" },
  "Start a claim or track your current and past claims.": { en: "Start a claim or track your current and past claims.", hi: "Claim shuru karein ya apne current aur purane claims track karein." },
  "CLAIMS": { en: "CLAIMS", hi: "CLAIMS" },
  "CLAIM DETAILS": { en: "CLAIM DETAILS", hi: "CLAIM DETAILS" },
  "Track claim": { en: "Track claim", hi: "Claim track karein" },
  "PF advance · Education": { en: "PF advance · Education", hi: "PF advance · Education" },
  "Your claim has been submitted. EPFO will review it next.": { en: "Your claim has been submitted. EPFO will review it next.", hi: "Aapka claim submit ho gaya hai. EPFO ise ab review karega." },
  "Employer verification is complete. EPFO review is in progress.": { en: "Employer verification is complete. EPFO review is in progress.", hi: "Employer verification complete hai. EPFO review chal raha hai." },
  "Paid to HDFC Bank •••• 4821 on 21 Feb 2025.": { en: "Paid to HDFC Bank •••• 4821 on 21 Feb 2025.", hi: "21 Feb 2025 ko HDFC Bank •••• 4821 mein payment hua." },
  "Scheme certificate issued after your Techcore employment ended.": { en: "Scheme certificate issued after your Techcore employment ended.", hi: "Techcore employment khatam hone ke baad scheme certificate issue hua." },
  "PF transfer": { en: "PF transfer", hi: "PF transfer" },
  Requested: { en: "Requested", hi: "Request kiya gaya" },
  "Employer verified": { en: "Employer verified", hi: "Employer verified" },
  "Your Techcore PF was transferred to your Infosys account.": { en: "Your Techcore PF was transferred to your Infosys account.", hi: "Aapka Techcore PF Infosys account mein transfer ho gaya." },
  Account: { en: "Account", hi: "Account" },
  "View profile details": { en: "View profile details", hi: "Profile details dekhein" },
  "Your EPFO identity and contact details.": { en: "Your EPFO identity and contact details.", hi: "Aapki EPFO identity aur contact details." },
  "MEMBER PROFILE": { en: "MEMBER PROFILE", hi: "MEMBER PROFILE" },
  "Personal details": { en: "Personal details", hi: "Personal details" },
  "Date of birth": { en: "Date of birth", hi: "Janm ki tareekh" },
  Gender: { en: "Gender", hi: "Gender" },
  "Father's name": { en: "Father's name", hi: "Pita ka naam" },
  "Marital status": { en: "Marital status", hi: "Marital status" },
  Male: { en: "Male", hi: "Purush" },
  Married: { en: "Married", hi: "Shaadishuda" },
  "Email ID": { en: "Email ID", hi: "Email ID" },
  "Correspondence address": { en: "Correspondence address", hi: "Patrachar ka pata" },
  "Permanent address": { en: "Permanent address", hi: "Sthayi pata" },
  "Profile updates use Aadhaar verification first. Review is only needed when it cannot confirm the change.": { en: "Profile updates use Aadhaar verification first. Review is only needed when it cannot confirm the change.", hi: "Profile updates pehle Aadhaar verification use karti hain. Review tabhi chahiye jab badlaav confirm na ho." },
  "Return home": { en: "Return home", hi: "Home par wapas jayein" },
  "Aadhaar verified": { en: "Aadhaar verified", hi: "Aadhaar verified" },
  "Your retirement savings, contributions and claims in one place.": { en: "Your retirement savings, contributions and claims in one place.", hi: "Aapki retirement savings, contributions aur claims, sab ek jagah." },
  "RETIREMENT ACCOUNT": { en: "RETIREMENT ACCOUNT", hi: "RETIREMENT ACCOUNT" },
  "Total PF balance": { en: "Total PF balance", hi: "Kul PF balance" },
  "This is your recorded PF balance, not an immediately claimable amount.": { en: "This is your recorded PF balance, not an immediately claimable amount.", hi: "Yeh aapka recorded PF balance hai, turant claim ki ja sakne wali rakam nahi." },
  "Recorded balance · Updated 28 Aug 2026": { en: "Recorded balance · Updated 28 Aug 2026", hi: "Recorded balance · 28 Aug 2026 ko update hua" },
  "Your contributions": { en: "Your contributions", hi: "Aapka contribution" },
  "Employer contributions": { en: "Employer contributions", hi: "Employer ka contribution" },
  "ACCOUNT HEALTH": { en: "ACCOUNT HEALTH", hi: "ACCOUNT KI STITHI" },
  "Everything is on track": { en: "Everything is on track", hi: "Sab kuch sahi chal raha hai" },
  "Your latest contribution arrived and your essential details are verified.": { en: "Your latest contribution arrived and your essential details are verified.", hi: "Aapka latest contribution aa gaya hai aur zaroori details verified hain." },
  "August contribution received": { en: "August contribution received", hi: "August ka contribution mil gaya" },
  "Aadhaar and bank verified": { en: "Aadhaar and bank verified", hi: "Aadhaar aur bank verified" },
  "Nominee registered": { en: "Nominee registered", hi: "Nominee registered hai" },
  "Previous PF transferred": { en: "Previous PF transferred", hi: "Purana PF transfer ho gaya" },
  "View account health": { en: "View account health", hi: "Account ki stithi dekhein" },
  "LATEST CONTRIBUTION": { en: "LATEST CONTRIBUTION", hi: "LATEST CONTRIBUTION" },
  "ACCOUNT MOVE": { en: "ACCOUNT MOVE", hi: "ACCOUNT MOVE" },
  "Deposited 18 August": { en: "Deposited 18 August", hi: "18 August ko deposit hua" },
  Confirmed: { en: "Confirmed", hi: "Confirm ho gaya" },
  "Most used actions": { en: "Most used actions", hi: "Sabse zyada use hone wale kaam" },
  "Keep your account ready and manage less frequent requests.": { en: "Keep your account ready and manage less frequent requests.", hi: "Apna account ready rakhein aur kabhi-kabhi wale requests manage karein." },
  "Keep your account ready": { en: "Keep your account ready", hi: "Apna account ready rakhein" },
  "KYC and bank details": { en: "KYC and bank details", hi: "KYC aur bank details" },
  "Your Aadhaar and HDFC Bank •••• 4821 are verified.": { en: "Your Aadhaar and HDFC Bank •••• 4821 are verified.", hi: "Aapka Aadhaar aur HDFC Bank •••• 4821 verified hai." },
  "Family and nomination": { en: "Family and nomination", hi: "Parivaar aur nomination" },
  "One nominee is registered.": { en: "One nominee is registered.", hi: "Ek nominee registered hai." },
  "Changing jobs": { en: "Changing jobs", hi: "Naukri badalna" },
  "Transfer previous PF": { en: "Transfer previous PF", hi: "Pichhla PF transfer karein" },
  "Your Techcore PF was transferred to Infosys.": { en: "Your Techcore PF was transferred to Infosys.", hi: "Aapka Techcore PF Infosys mein transfer ho gaya." },
  "Track transfer": { en: "Track transfer", hi: "Transfer track karein" },
  "Profile details": { en: "Profile details", hi: "Profile details" },
  "Your personal details match your Aadhaar.": { en: "Your personal details match your Aadhaar.", hi: "Aapki personal details Aadhaar se match karti hain." },
  "Service updates are simulated in this prototype.": { en: "Service updates are simulated in this prototype.", hi: "Is prototype mein service updates simulated hain." },
  "Updates and requests": { en: "Updates and requests", hi: "Updates aur requests" },
  "SERVICE REQUESTS": { en: "SERVICE REQUESTS", hi: "SERVICE REQUESTS" },
  "No update requests in progress.": { en: "No update requests in progress.", hi: "Koi update request progress mein nahi hai." },
  "Account documents": { en: "Account documents", hi: "Account documents" },
  "View or download your verified UAN identity card.": { en: "View or download your verified UAN identity card.", hi: "Apna verified UAN identity card dekhein ya download karein." },
  Available: { en: "Available", hi: "Available" },
  "Aadhaar, PAN and HDFC Bank •••• 4821 are verified.": { en: "Aadhaar, PAN and HDFC Bank •••• 4821 are verified.", hi: "Aadhaar, PAN aur HDFC Bank •••• 4821 verified hain." },
  "Update KYC or bank": { en: "Update KYC or bank", hi: "KYC ya bank update karein" },
  "Bank validation": { en: "Bank validation", hi: "Bank validation" },
  "Bank validation in progress": { en: "Bank validation in progress", hi: "Bank validation chal raha hai" },
  "Bank account number": { en: "Bank account number", hi: "Bank account number" },
  "IFSC code": { en: "IFSC code", hi: "IFSC code" },
  "Employer approval": { en: "Employer approval", hi: "Employer approval" },
  "Contact details": { en: "Contact details", hi: "Contact details" },
  "Your mobile number and email are verified.": { en: "Your mobile number and email are verified.", hi: "Aapka mobile number aur email verified hai." },
  "Update contact details": { en: "Update contact details", hi: "Contact details update karein" },
  "Mobile number": { en: "Mobile number", hi: "Mobile number" },
  "Email address": { en: "Email address", hi: "Email address" },
  "OTP verification": { en: "OTP verification", hi: "OTP verification" },
  Updated: { en: "Updated", hi: "Update ho gaya" },
  "Verification pending": { en: "Verification pending", hi: "Verification pending hai" },
  Registered: { en: "Registered", hi: "Registered" },
  "Change nomination": { en: "Change nomination", hi: "Nomination badlein" },
  "Nominee name": { en: "Nominee name", hi: "Nominee ka naam" },
  Relationship: { en: "Relationship", hi: "Rishta" },
  "Ready for e-Sign": { en: "Ready for e-Sign", hi: "e-Sign ke liye ready" },
  "Update profile": { en: "Update profile", hi: "Profile update karein" },
  "Most profile details can be updated with Aadhaar verification.": { en: "Most profile details can be updated with Aadhaar verification.", hi: "Zyadatar profile details Aadhaar verification se update ho sakti hain." },
  "Aadhaar validation in progress": { en: "Aadhaar validation in progress", hi: "Aadhaar validation chal raha hai" },
  "If Aadhaar verification cannot confirm the change": { en: "If Aadhaar verification cannot confirm the change", hi: "Agar Aadhaar verification badlaav confirm na kar sake" },
  "Needs review": { en: "Needs review", hi: "Review chahiye" },
  "Detail to correct": { en: "Detail to correct", hi: "Sahi karne wali detail" },
  "Correct value": { en: "Correct value", hi: "Sahi value" },
  "Employer review": { en: "Employer review", hi: "Employer review" },
  "EPFO decision": { en: "EPFO decision", hi: "EPFO decision" },
  "Awaiting employer review": { en: "Awaiting employer review", hi: "Employer review ka intezaar" },
  "UPDATE REQUEST": { en: "UPDATE REQUEST", hi: "UPDATE REQUEST" },
  "Enter the details for your request.": { en: "Enter the details for your request.", hi: "Apni request ki details daalein." },
  "Review your request before submitting.": { en: "Review your request before submitting.", hi: "Submit karne se pehle request review karein." },
  "Your request will follow this status path:": { en: "Your request will follow this status path:", hi: "Aapki request ye status path follow karegi:" },
  "Submit request": { en: "Submit request", hi: "Request submit karein" },
  "Official EPFO services, in plain language": { en: "Official EPFO services, in plain language", hi: "Official EPFO services, aasaan bhasha mein" },
  "File a Claim": { en: "File a Claim", hi: "Claim file karein" },
  "Start a new PF claim": { en: "Start a new PF claim", hi: "Naya PF claim shuru karein" },
  "Back to dashboard": { en: "Back to dashboard", hi: "Dashboard par wapas jayein" },
  "Submit a claim": { en: "Submit a claim", hi: "Claim submit karein" },
  "Answer only what is needed. We’ll prepare the right EPFO form for you.": { en: "Answer only what is needed. We’ll prepare the right EPFO form for you.", hi: "Sirf zaroori sawaalon ka jawab dein. Hum aapke liye sahi EPFO form taiyaar karenge." },
  "Choose claim": { en: "Choose claim", hi: "Claim chunein" },
  "Confirm details": { en: "Confirm details", hi: "Details confirm karein" },
  "Claim questions": { en: "Claim questions", hi: "Claim ke sawaal" },
  "Review and submit": { en: "Review and submit", hi: "Review karke submit karein" },
  "Complete the required fields to continue.": { en: "Complete the required fields to continue.", hi: "Aage badhne ke liye zaroori fields poore karein." },
  "Confirm your bank account and enter the 6-digit OTP.": { en: "Confirm your bank account and enter the 6-digit OTP.", hi: "Bank account confirm karke 6-digit OTP daalein." },
  "Verify your bank account through Account Aggregator and enter the 6-digit OTP.": { en: "Verify your bank account through Account Aggregator and enter the 6-digit OTP.", hi: "Account Aggregator se bank account verify karke 6-digit OTP daalein." },
  "Verification required": { en: "Verification required", hi: "Verification zaroori hai" },
  "Verify payment account": { en: "Verify payment account", hi: "Payment account verify karein" },
  "Re-enter your bank account details to verify them for this claim.": { en: "Re-enter your bank account details to verify them for this claim.", hi: "Is claim ke liye verify karne ko bank details phir se daalein." },
  "Enter a valid bank account number and IFSC code.": { en: "Enter a valid bank account number and IFSC code.", hi: "Sahi bank account number aur IFSC code daalein." },
  "Verify through Account Aggregator": { en: "Verify through Account Aggregator", hi: "Account Aggregator se verify karein" },
  "This prototype uses a one-time Account Aggregator consent flow. It does not connect to a bank or EPFO.": { en: "This prototype uses a one-time Account Aggregator consent flow. It does not connect to a bank or EPFO.", hi: "Yeh prototype one-time Account Aggregator consent flow use karta hai. Yeh bank ya EPFO se connect nahi hota." },
  "Review consent": { en: "Review consent", hi: "Consent review karein" },
  "Account Aggregator shares data only after your approval.": { en: "Account Aggregator shares data only after your approval.", hi: "Account Aggregator aapki approval ke baad hi data share karta hai." },
  Recipient: { en: "Recipient", hi: "Recipient" },
  Purpose: { en: "Purpose", hi: "Purpose" },
  "Data requested": { en: "Data requested", hi: "Maanga gaya data" },
  Duration: { en: "Duration", hi: "Avadhi" },
  "EPFO claim payment verification (prototype)": { en: "EPFO claim payment verification (prototype)", hi: "EPFO claim payment verification (prototype)" },
  "Verify your payment account for this claim": { en: "Verify your payment account for this claim", hi: "Is claim ke liye payment account verify karein" },
  "Account holder name, account number, IFSC and account status": { en: "Account holder name, account number, IFSC and account status", hi: "Account holder naam, account number, IFSC aur account status" },
  "One time": { en: "One time", hi: "Ek baar" },
  "I consent to share these bank details for this claim only.": { en: "I consent to share these bank details for this claim only.", hi: "Main sirf is claim ke liye bank details share karne ki consent deta hoon." },
  "Continue to Account Aggregator": { en: "Continue to Account Aggregator", hi: "Account Aggregator par jaari rakhein" },
  "Verifying account through Account Aggregator": { en: "Verifying account through Account Aggregator", hi: "Account Aggregator se account verify ho raha hai" },
  "Your bank is responding to your one-time consent request.": { en: "Your bank is responding to your one-time consent request.", hi: "Aapka bank aapki one-time consent request ka response de raha hai." },
  "Bank account verified": { en: "Bank account verified", hi: "Bank account verify ho gaya" },
  "HDFC Bank account ending {lastFour} is verified for this claim.": { en: "HDFC Bank account ending {lastFour} is verified for this claim.", hi: "HDFC Bank account jo {lastFour} par khatam hota hai, is claim ke liye verified hai." },
  Change: { en: "Change", hi: "Badlein" },
  Back: { en: "Back", hi: "Wapas" },
  Continue: { en: "Continue", hi: "Aage badhein" },
  "Submit claim": { en: "Submit claim", hi: "Claim submit karein" },
  "What would you like to claim?": { en: "What would you like to claim?", hi: "Aap kaunsa claim karna chahte hain?" },
  "Choose one option. You can review everything before submitting.": { en: "Choose one option. You can review everything before submitting.", hi: "Ek option chunein. Submit karne se pehle sab review kar sakte hain." },
  "PF advance": { en: "PF advance", hi: "PF advance" },
  "Claim part of your PF for an eligible need": { en: "Claim part of your PF for an eligible need", hi: "Eligible zaroorat ke liye PF ka kuch hissa claim karein" },
  "Final PF settlement": { en: "Final PF settlement", hi: "Final PF settlement" },
  "Settle your PF after leaving employment": { en: "Settle your PF after leaving employment", hi: "Naukri chhodne ke baad PF settle karein" },
  "Pension benefit": { en: "Pension benefit", hi: "Pension benefit" },
  "Request an EPS benefit or scheme certificate": { en: "Request an EPS benefit or scheme certificate", hi: "EPS benefit ya scheme certificate maangein" },
  "Confirm your details": { en: "Confirm your details", hi: "Apni details confirm karein" },
  "These details come from your UAN and verified KYC records.": { en: "These details come from your UAN and verified KYC records.", hi: "Ye details aapke UAN aur verified KYC records se aayi hain." },
  UAN: { en: "UAN", hi: "UAN" },
  Employer: { en: "Employer", hi: "Employer" },
  "Date of joining": { en: "Date of joining", hi: "Joining ki tareekh" },
  "Date of leaving": { en: "Date of leaving", hi: "Leaving ki tareekh" },
  "Currently employed": { en: "Currently employed", hi: "Abhi naukri mein hain" },
  "Bank account": { en: "Bank account", hi: "Bank account" },
  "These details are correct": { en: "These details are correct", hi: "Ye details sahi hain" },
  "A few details about your claim": { en: "A few details about your claim", hi: "Aapke claim ke baare mein kuch details" },
  "We only ask questions needed for your selected claim.": { en: "We only ask questions needed for your selected claim.", hi: "Hum sirf aapke chune hue claim ke zaroori sawaal poochte hain." },
  "Purpose of advance": { en: "Purpose of advance", hi: "Advance ka purpose" },
  "Select a purpose": { en: "Select a purpose", hi: "Purpose chunein" },
  "Amount requested": { en: "Amount requested", hi: "Maangi gayi rakam" },
  Illness: { en: "Illness", hi: "Bimari" },
  Housing: { en: "Housing", hi: "Ghar" },
  Marriage: { en: "Marriage", hi: "Shaadi" },
  Education: { en: "Education", hi: "Padhai" },
  "Natural calamity": { en: "Natural calamity", hi: "Prakritik aapda" },
  "Electricity cut": { en: "Electricity cut", hi: "Bijli cut" },
  "Assistive equipment": { en: "Assistive equipment", hi: "Sahayak equipment" },
  "Patient and relationship": { en: "Patient and relationship", hi: "Patient aur rishta" },
  "Housing requirement": { en: "Housing requirement", hi: "Ghar ki zaroorat" },
  "Beneficiary and relationship": { en: "Beneficiary and relationship", hi: "Beneficiary aur rishta" },
  "Student and course": { en: "Student and course", hi: "Student aur course" },
  "Date and place affected": { en: "Date and place affected", hi: "Prabhavit tareekh aur jagah" },
  "Outage period": { en: "Outage period", hi: "Bijli band rehne ka samay" },
  "Equipment required": { en: "Equipment required", hi: "Zaroori equipment" },
  "Tax declaration": { en: "Tax declaration", hi: "Tax declaration" },
  "Select one": { en: "Select one", hi: "Ek chunein" },
  "Not applicable": { en: "Not applicable", hi: "Laagu nahi" },
  "Choose Form 15G or 15H only if it applies to your tax situation.": { en: "Choose Form 15G or 15H only if it applies to your tax situation.", hi: "Form 15G ya 15H tabhi chunein jab aapki tax situation mein laagu ho." },
  "Pension claim benefit": { en: "Pension claim benefit", hi: "Pension claim benefit" },
  "Scheme certificate": { en: "Scheme certificate", hi: "Scheme certificate" },
  "Receive the eligible pension claim amount": { en: "Receive the eligible pension claim amount", hi: "Eligible pension claim amount paayein" },
  "Preserve your pension service for the future": { en: "Preserve your pension service for the future", hi: "Pension service ko future ke liye bachayein" },
  "We generated the required legacy form data from your answers.": { en: "We generated the required legacy form data from your answers.", hi: "Aapke jawaabon se zaroori purane form ka data taiyaar ho gaya hai." },
  "Claim type": { en: "Claim type", hi: "Claim type" },
  "EPFO form": { en: "EPFO form", hi: "EPFO form" },
  "Claim details": { en: "Claim details", hi: "Claim details" },
  "Payment account": { en: "Payment account", hi: "Payment account" },
  "I confirm this bank account for payment": { en: "I confirm this bank account for payment", hi: "Main payment ke liye is bank account ko confirm karta hoon" },
  "Aadhaar verification": { en: "Aadhaar verification", hi: "Aadhaar verification" },
  "An OTP will be sent to your Aadhaar-linked mobile number ending 8842.": { en: "An OTP will be sent to your Aadhaar-linked mobile number ending 8842.", hi: "OTP aapke Aadhaar-linked mobile number 8842 par bheja jayega." },
  "Send OTP": { en: "Send OTP", hi: "OTP bhejein" },
  "6-digit OTP": { en: "6-digit OTP", hi: "6-digit OTP" },
  "CLAIM SUBMITTED": { en: "CLAIM SUBMITTED", hi: "CLAIM SUBMIT HO GAYA" },
  "Your claim has been submitted": { en: "Your claim has been submitted", hi: "Aapka claim submit ho gaya hai" },
  "EPFO will review your claim. You can track its progress from Past Claim Status.": { en: "EPFO will review your claim. You can track its progress from Past Claim Status.", hi: "EPFO aapka claim review karega. Past Claim Status se progress track kar sakte hain." },
  "Claim reference": { en: "Claim reference", hi: "Claim reference" },
  "Past Claim Status": { en: "Past Claim Status", hi: "Purane claim ka status" },
  "Track your previous claims": { en: "Track your previous claims", hi: "Apne purane claims track karein" },
  "View Passbook": { en: "View Passbook", hi: "Passbook dekhein" },
  "Your PF credits and debits in one place.": { en: "Your PF credits and debits in one place.", hi: "Aapke PF credits aur debits, ek jagah." },
  "Member ID": { en: "Member ID", hi: "Member ID" },
  "Financial year": { en: "Financial year", hi: "Financial year" },
  Date: { en: "Date", hi: "Tareekh" },
  Particulars: { en: "Particulars", hi: "Vivaran" },
  Credit: { en: "Credit", hi: "Credit" },
  Debit: { en: "Debit", hi: "Debit" },
  "Opening balance": { en: "Opening balance", hi: "Shuruaati balance" },
  "Total credits": { en: "Total credits", hi: "Kul credits" },
  "Total debits": { en: "Total debits", hi: "Kul debits" },
  "Closing balance": { en: "Closing balance", hi: "Antim balance" },
  "View transactions": { en: "View transactions", hi: "Transactions dekhein" },
  "See every contribution and credit": { en: "See every contribution and credit", hi: "Har contribution aur credit dekhein" },
  "Check claim eligibility": { en: "Check claim eligibility", hi: "Claim eligibility check karein" },
  "Know what you can claim first": { en: "Know what you can claim first", hi: "Pehle jaanein ki kitna claim kar sakte hain" },
  "Bring old PF together": { en: "Bring old PF together", hi: "Purana PF saath laayein" },
  "Transfer a previous account": { en: "Transfer a previous account", hi: "Pichhla account transfer karein" },
  PASSBOOK: { en: "PASSBOOK", hi: "PASSBOOK" },
  "Recent activity": { en: "Recent activity", hi: "Haal ke transactions" },
  "View all transactions": { en: "View all transactions", hi: "Saare transactions dekhein" },
  "August contribution": { en: "August contribution", hi: "August ka contribution" },
  "July contribution": { en: "July contribution", hi: "July ka contribution" },
  "Annual interest credit": { en: "Annual interest credit", hi: "Saalana interest credit" },
  "Medical advance": { en: "Medical advance", hi: "Medical advance" },
  "Submitted 12 Aug · HDFC Bank •••• 4821": { en: "Submitted 12 Aug · HDFC Bank •••• 4821", hi: "12 Aug ko submit hua · HDFC Bank •••• 4821" },
  Verified: { en: "Verified", hi: "Verified" },
  "No action needed.": { en: "No action needed.", hi: "Aapko kuch karne ki zaroorat nahi." },
  "EPFO is reviewing your request. Your employer verification is complete.": { en: "EPFO is reviewing your request. Your employer verification is complete.", hi: "EPFO aapki request review kar raha hai. Employer verification complete hai." },
  EMPLOYMENT: { en: "EMPLOYMENT", hi: "NAUKRI" },
  "Your PF follows you across jobs": { en: "Your PF follows you across jobs", hi: "Naukri badalne par bhi aapka PF aapke saath rehta hai" },
  "View employment history": { en: "View employment history", hi: "Naukri ki history dekhein" },
  "Employment history": { en: "Employment history", hi: "Naukri ki history" },
  "Your connected employment accounts and PF transfers.": { en: "Your connected employment accounts and PF transfers.", hi: "Aapke connected employment accounts aur PF transfers." },
  "Connected employment accounts": { en: "Connected employment accounts", hi: "Connected employment accounts" },
  "Current · Contributions arriving normally": { en: "Current · Contributions arriving normally", hi: "Current · Contributions theek se aa rahe hain" },
  "PF transferred": { en: "PF transferred", hi: "PF transfer ho gaya" },
  "UAN card": { en: "UAN card", hi: "UAN card" },
  "View UAN card": { en: "View UAN card", hi: "UAN card dekhein" },
  Balance: { en: "Balance", hi: "Balance" },
  "Flip back to balance": { en: "Flip back to balance", hi: "Balance par wapas jayein" },
  "Download UAN card as PDF": { en: "Download UAN card as PDF", hi: "UAN card PDF download karein" },
  "Universal Account Number": { en: "Universal Account Number", hi: "Universal Account Number" },
  Name: { en: "Name", hi: "Naam" },
  "Father's Name": { en: "Father's Name", hi: "Pita ka naam" },
  "KYC Status": { en: "KYC Status", hi: "KYC status" },
  Yes: { en: "Yes", hi: "Haan" },
  Photograph: { en: "Photograph", hi: "Photo" },
  "Issued 24 Aug 2026": { en: "Issued 24 Aug 2026", hi: "24 Aug 2026 ko issue hua" },
  "PF BALANCE": { en: "PF BALANCE", hi: "PF BALANCE" },
  "View UAN ID card": { en: "View UAN ID card", hi: "UAN ID card dekhein" },
  "UAN ID card": { en: "UAN ID card", hi: "UAN ID card" },
  "Back to PF balance": { en: "Back to PF balance", hi: "PF balance par wapas jayein" },
  "Download PDF": { en: "Download PDF", hi: "PDF download karein" },
  "My employment": { en: "My employment", hi: "Meri naukri" },
  "KYC & profile": { en: "KYC & profile", hi: "KYC aur profile" },
  Nomination: { en: "Nomination", hi: "Nomination" },
  Documents: { en: "Documents", hi: "Documents" },
  Employees: { en: "Employees", hi: "Karmachari" },
  "ECR & contributions": { en: "ECR & contributions", hi: "ECR aur contribution" },
  Payments: { en: "Payments", hi: "Bhugtan" },
  Compliance: { en: "Compliance", hi: "Compliance" },
  Reports: { en: "Reports", hi: "Reports" },
  "Users & access": { en: "Users & access", hi: "Users aur access" },
  "Compliance guide": { en: "Compliance guide", hi: "Compliance guide" },
  "Contract employers": { en: "Contract employers", hi: "Contract employers" },
  "Work orders": { en: "Work orders", hi: "Work orders" },
  "Contract workers": { en: "Contract workers", hi: "Contract workers" },
  "Your total PF balance": { en: "Your total PF balance", hi: "Aapka total PF balance" },
  "₹8,430 contribution in August": { en: "₹8,430 contribution in August", hi: "August mein ₹8,430 contribution" },
  "Last updated 18 Aug 2026": { en: "Last updated 18 Aug 2026", hi: "Aakhri update 18 Aug 2026" },
  "Employee share": { en: "Employee share", hi: "Employee ka hissa" },
  "Employer share": { en: "Employer share", hi: "Employer ka hissa" },
  "Quick actions": { en: "Quick actions", hi: "Jaldi ke kaam" },
  "Most-used services": { en: "Most-used services", hi: "Sabse zyada use hone wali services" },
  "View passbook": { en: "View passbook", hi: "Passbook dekhein" },
  "See every contribution": { en: "See every contribution", hi: "Har contribution dekhein" },
  "File a PF claim": { en: "File a PF claim", hi: "PF claim file karein" },
  "Start or track a claim": { en: "Start or track a claim", hi: "Claim shuru karein ya track karein" },
  "Update KYC": { en: "Update KYC", hi: "KYC update karein" },
  "Keep details verified": { en: "Keep details verified", hi: "Details verified rakhein" },
  "Add nomination": { en: "Add nomination", hi: "Nomination add karein" },
  "Protect your family": { en: "Protect your family", hi: "Apne parivaar ko surakshit karein" },
  "MY EMPLOYMENT": { en: "MY EMPLOYMENT", hi: "MERI NAUKRI" },
  "3 linked employers": { en: "3 linked employers", hi: "3 jude hue employers" },
  "View all": { en: "View all", hi: "Sab dekhein" },
  "Current employment": { en: "Current employment", hi: "Abhi ki naukri" },
  "PF transferred successfully": { en: "PF transferred successfully", hi: "PF successfully transfer ho gaya" },
  Transferred: { en: "Transferred", hi: "Transfer ho gaya" },
  Active: { en: "Active", hi: "Active" },
  "LATEST CLAIM": { en: "LATEST CLAIM", hi: "NAYA CLAIM" },
  "Claim progress": { en: "Claim progress", hi: "Claim ki progress" },
  "In review": { en: "In review", hi: "Review mein" },
  "Advance claim · Submitted 12 Aug": { en: "Advance claim · Submitted 12 Aug", hi: "Advance claim · 12 Aug ko submit hua" },
  Submitted: { en: "Submitted", hi: "Submit ho gaya" },
  Verification: { en: "Verification", hi: "Verification" },
  Review: { en: "Review", hi: "Review" },
  Paid: { en: "Paid", hi: "Paid" },
  "Your employer verification is complete. EPFO review is in progress.": { en: "Your employer verification is complete. EPFO review is in progress.", hi: "Aapke employer ki verification complete ho gayi hai. EPFO review chal raha hai." },
  "Active employees": { en: "Active employees", hi: "Active karmachari" },
  "+42 this month": { en: "+42 this month", hi: "Is mahine +42" },
  "ECR status": { en: "ECR status", hi: "ECR status" },
  "Payment due 15 Sep": { en: "Payment due 15 Sep", hi: "Payment 15 Sep tak" },
  Good: { en: "Good", hi: "Achha" },
  "No action required": { en: "No action required", hi: "Koi action zaroori nahi" },
  "Contribution filing": { en: "Contribution filing", hi: "Contribution filing" },
  "Employees included": { en: "Employees included", hi: "Kitne karmachari" },
  "Gross wages": { en: "Gross wages", hi: "Gross wages" },
  "Submission signed by the Authorized Signatory on 18 August.": { en: "Submission signed by the Authorized Signatory on 18 August.", hi: "Submission Authorized Signatory ne 18 August ko sign kiya." },
  ATTENTION: { en: "ATTENTION", hi: "DHYAAN DEIN" },
  "Tasks to complete": { en: "Tasks to complete", hi: "Kaam baaki hain" },
  "Awaiting employer approval": { en: "Awaiting employer approval", hi: "Employer ki approval ka intezaar" },
  "Last working day to confirm": { en: "Last working day to confirm", hi: "Aakhri working day pe confirm karein" },
  "RECENT ACTIVITY": { en: "RECENT ACTIVITY", hi: "HAL KI ACTIVITY" },
  "August ECR submitted": { en: "August ECR submitted", hi: "August ECR submit hua" },
  "July payment reconciled": { en: "July payment reconciled", hi: "July ka payment reconcile hua" },
  Complete: { en: "Complete", hi: "Complete" },
  Matched: { en: "Matched", hi: "Match ho gaya" },
  "PRINCIPAL EMPLOYER SERVICES": { en: "PRINCIPAL EMPLOYER SERVICES", hi: "PRINCIPAL EMPLOYER SERVICES" },
  "ESTABLISHMENT SERVICES": { en: "ESTABLISHMENT SERVICES", hi: "ESTABLISHMENT SERVICES" },
  "No action is available here yet.": { en: "No action is available here yet.", hi: "Yahan abhi koi action available nahi hai." },
  "REQUEST TRACKER": { en: "REQUEST TRACKER", hi: "REQUEST TRACKER" },
  "Requests in this service": { en: "Requests in this service", hi: "Is service ke requests" },
  "{id} · Submitted {date}": { en: "{id} · Submitted {date}", hi: "{id} · {date} ko submit hua" },
  "Compliance review in progress": { en: "Compliance review in progress", hi: "Compliance review chal raha hai" },
  "Employer validation in progress": { en: "Employer validation in progress", hi: "Employer validation chal raha hai" },
  "EMPLOYER SERVICE": { en: "EMPLOYER SERVICE", hi: "EMPLOYER SERVICE" },
  "Prototype only. Nothing is sent to EPFO or a third party.": { en: "Prototype only. Nothing is sent to EPFO or a third party.", hi: "Sirf prototype hai. Kuch bhi EPFO ya kisi third party ko nahi bheja jaata." },
  "Choose file in a live service": { en: "Choose file in a live service", hi: "Live service mein file chunein" },
  "Enter {field}": { en: "Enter {field}", hi: "{field} darj karein" },
  "Preview request": { en: "Preview request", hi: "Request preview karein" },
  "REQUEST PREVIEW": { en: "REQUEST PREVIEW", hi: "REQUEST PREVIEW" },
  "Provided for review": { en: "Provided for review", hi: "Review ke liye diya gaya" },
  "Back to edit": { en: "Back to edit", hi: "Edit par wapas jaayein" },
  "Submitting your request": { en: "Submitting your request", hi: "Aapki request submit ho rahi hai" },
  "Validating the details and preparing the employer record.": { en: "Validating the details and preparing the employer record.", hi: "Details verify ho rahi hain aur employer record taiyaar ho raha hai." },
  "Request submitted": { en: "Request submitted", hi: "Request submit ho gayi" },
  "Your prototype request is ready for the relevant EPFO workflow.": { en: "Your prototype request is ready for the relevant EPFO workflow.", hi: "Aapki prototype request sambandhit EPFO workflow ke liye taiyaar hai." },
  Done: { en: "Done", hi: "Ho gaya" },
  "Register employee": { en: "Register employee", hi: "Employee register karein" },
  "Create a UAN-linked member record before the next ECR.": { en: "Create a UAN-linked member record before the next ECR.", hi: "Agle ECR se pehle ek UAN-linked member record banayein." },
  "The member receives a UAN activation prompt after validation.": { en: "The member receives a UAN activation prompt after validation.", hi: "Validation ke baad member ko UAN activation prompt milta hai." },
  "Approve profile update": { en: "Approve profile update", hi: "Profile update approve karein" },
  "Review a member’s pending KYC or profile correction.": { en: "Review a member’s pending KYC or profile correction.", hi: "Member ki pending KYC ya profile correction review karein." },
  "Only authorised establishment users can approve this request.": { en: "Only authorised establishment users can approve this request.", hi: "Sirf authorised establishment users hi is request ko approve kar sakte hain." },
  "Upload ECR": { en: "Upload ECR", hi: "ECR upload karein" },
  "Submit the monthly Electronic Challan-cum-Return file.": { en: "Submit the monthly Electronic Challan-cum-Return file.", hi: "Mahine ki Electronic Challan-cum-Return file submit karein." },
  "ECR is UAN-based. The preview creates a mock TRRN only.": { en: "ECR is UAN-based. The preview creates a mock TRRN only.", hi: "ECR UAN-based hota hai. Yeh preview sirf mock TRRN banata hai." },
  "Generate challan": { en: "Generate challan", hi: "Challan generate karein" },
  "Prepare payment for a submitted ECR or arrear return.": { en: "Prepare payment for a submitted ECR or arrear return.", hi: "Submit hui ECR ya arrear return ke liye payment taiyaar karein." },
  "A challan is generated after ECR validation.": { en: "A challan is generated after ECR validation.", hi: "ECR validation ke baad challan generate hota hai." },
  "Pay actionable challan": { en: "Pay actionable challan", hi: "Actionable challan pay karein" },
  "Complete a payment against an approved TRRN.": { en: "Complete a payment against an approved TRRN.", hi: "Approved TRRN ke against payment complete karein." },
  "This prototype never opens a bank payment page.": { en: "This prototype never opens a bank payment page.", hi: "Yeh prototype kabhi bank payment page nahi kholta." },
  "Submit compliance response": { en: "Submit compliance response", hi: "Compliance response submit karein" },
  "Attach a reply to a compliance item for the establishment.": { en: "Attach a reply to a compliance item for the establishment.", hi: "Establishment ke compliance item ka reply attach karein." },
  "The response remains a local prototype record.": { en: "The response remains a local prototype record.", hi: "Yeh response sirf local prototype record rehta hai." },
  "Request establishment e-report card": { en: "Request establishment e-report card", hi: "Establishment e-report card request karein" },
  "Prepare a compliance and contribution summary.": { en: "Prepare a compliance and contribution summary.", hi: "Compliance aur contribution summary taiyaar karein." },
  "The generated report is a preview only.": { en: "The generated report is a preview only.", hi: "Generate hua report sirf preview hai." },
  "Find TRRN": { en: "Find TRRN", hi: "TRRN dhoondhein" },
  "Look up a challan or ECR by its transaction reference.": { en: "Look up a challan or ECR by its transaction reference.", hi: "Transaction reference se challan ya ECR dhoondhein." },
  "Use the reference issued after ECR submission.": { en: "Use the reference issued after ECR submission.", hi: "ECR submission ke baad mile reference ka istemal karein." },
  "Add authorised user": { en: "Add authorised user", hi: "Authorised user add karein" },
  "Invite an establishment user with a defined operational role.": { en: "Invite an establishment user with a defined operational role.", hi: "Ek defined operational role ke saath establishment user invite karein." },
  "Authorisation is simulated; no user is invited outside this browser.": { en: "Authorisation is simulated; no user is invited outside this browser.", hi: "Authorisation simulate hota hai; is browser ke bahar koi user invite nahi hota." },
  "Link contract employer": { en: "Link contract employer", hi: "Contract employer link karein" },
  "Associate a contract employer with this principal employer.": { en: "Associate a contract employer with this principal employer.", hi: "Is principal employer ke saath ek contract employer jodein." },
  "EPFO’s principal-employer facility uses these links for compliance oversight.": { en: "EPFO’s principal-employer facility uses these links for compliance oversight.", hi: "EPFO ki principal-employer facility in links ka istemal compliance oversight ke liye karti hai." },
  "Add work order": { en: "Add work order", hi: "Work order add karein" },
  "Record an outsourced job contract for a linked employer.": { en: "Record an outsourced job contract for a linked employer.", hi: "Linked employer ke liye outsourced job contract record karein." },
  "Upload supporting documents only in the prototype browser session.": { en: "Upload supporting documents only in the prototype browser session.", hi: "Supporting documents sirf is prototype browser session mein upload karein." },
  "Declare contract workers": { en: "Declare contract workers", hi: "Contract workers declare karein" },
  "Record contract-worker information against a work order.": { en: "Record contract-worker information against a work order.", hi: "Ek work order ke against contract-worker information record karein." },
  "This supports coverage and contribution compliance monitoring.": { en: "This supports coverage and contribution compliance monitoring.", hi: "Yeh coverage aur contribution compliance monitoring mein madad karta hai." },
  "Review contractor compliance": { en: "Review contractor compliance", hi: "Contractor compliance review karein" },
  "Record a compliance follow-up for a linked contract employer.": { en: "Record a compliance follow-up for a linked contract employer.", hi: "Linked contract employer ke liye compliance follow-up record karein." },
  "The review is recorded locally in this prototype.": { en: "The review is recorded locally in this prototype.", hi: "Yeh review is prototype mein locally record hota hai." },
  "Request contractor summary": { en: "Request contractor summary", hi: "Contractor summary request karein" },
  "Prepare a work-order and contractor compliance view.": { en: "Prepare a work-order and contractor compliance view.", hi: "Work-order aur contractor compliance view taiyaar karein." },
  "The report is a prototype preview.": { en: "The report is a prototype preview.", hi: "Yeh report ek prototype preview hai." },
  "Employee name": { en: "Employee name", hi: "Employee ka naam" },
  "Aadhaar / UAN": { en: "Aadhaar / UAN", hi: "Aadhaar / UAN" },
  "Request reference": { en: "Request reference", hi: "Request reference" },
  "Wage month": { en: "Wage month", hi: "Wage month" },
  "Salary disbursal date": { en: "Salary disbursal date", hi: "Salary disbursal ki tareekh" },
  "ECR file": { en: "ECR file", hi: "ECR file" },
  TRRN: { en: "TRRN", hi: "TRRN" },
  "Payment mode": { en: "Payment mode", hi: "Payment mode" },
  "Banking channel": { en: "Banking channel", hi: "Banking channel" },
  "Reference number": { en: "Reference number", hi: "Reference number" },
  "Response document": { en: "Response document", hi: "Response document" },
  "Reporting period": { en: "Reporting period", hi: "Reporting period" },
  "User name": { en: "User name", hi: "User ka naam" },
  "Registered mobile": { en: "Registered mobile", hi: "Registered mobile" },
  Role: { en: "Role", hi: "Role" },
  "Contract employer name": { en: "Contract employer name", hi: "Contract employer ka naam" },
  "EPFO establishment code": { en: "EPFO establishment code", hi: "EPFO establishment code" },
  "Contract period": { en: "Contract period", hi: "Contract period" },
  "Work order number": { en: "Work order number", hi: "Work order number" },
  "Contract employer": { en: "Contract employer", hi: "Contract employer" },
  "Start and end dates": { en: "Start and end dates", hi: "Shuru aur khatam hone ki tareekhein" },
  "Worker count": { en: "Worker count", hi: "Workers ki ginti" },
  Observation: { en: "Observation", hi: "Observation" },
  "Close compliance guide": { en: "Close compliance guide", hi: "Compliance guide band karein" },
  "Resize compliance guide panel": { en: "Resize compliance guide panel", hi: "Compliance guide panel resize karein" },
  "{role} GUIDE · PREVIEW": { en: "{role} GUIDE · PREVIEW", hi: "{role} GUIDE · PREVIEW" },
  "Your compliance agent": { en: "Your compliance agent", hi: "Aapka compliance agent" },
  "It reads this account and checks it against EPFO's own filing and compliance norms. It never files, confirms or submits anything without your approval.": { en: "It reads this account and checks it against EPFO's own filing and compliance norms. It never files, confirms or submits anything without your approval.", hi: "Yeh is account ko padhta hai aur EPFO ke apne filing aur compliance norms se check karta hai. Yeh aapki approval ke bina kabhi kuch file, confirm ya submit nahi karta." },
  "Scanning this account": { en: "Scanning this account", hi: "Yeh account scan ho raha hai" },
  "Checking ECR filing, contribution due dates and compliance tasks…": { en: "Checking ECR filing, contribution due dates and compliance tasks…", hi: "ECR filing, contribution due dates aur compliance tasks check kiye ja rahe hain…" },
  "← Back to tasks": { en: "← Back to tasks", hi: "← Tasks par wapas jaayein" },
  "CONFIRM BEFORE CONTINUING": { en: "CONFIRM BEFORE CONTINUING", hi: "AAGE BADHNE SE PEHLE CONFIRM KAREIN" },
  Reversible: { en: "Reversible", hi: "Reversible" },
  Irreversible: { en: "Irreversible", hi: "Irreversible" },
  "What will happen": { en: "What will happen", hi: "Kya hoga" },
  "Open the relevant workspace. Nothing is filed or confirmed here.": { en: "Open the relevant workspace. Nothing is filed or confirmed here.", hi: "Sambandhit workspace khulega. Yahan kuch file ya confirm nahi hota." },
  "Your control": { en: "Your control", hi: "Aapka control" },
  "You review each record and submit the actual request separately.": { en: "You review each record and submit the actual request separately.", hi: "Aap har record review karke asli request alag se submit karte hain." },
  "I understand — continue": { en: "I understand — continue", hi: "Samajh gaya — aage badhein" },
  Cancel: { en: "Cancel", hi: "Cancel karein" },
  "ACCOUNT INSIGHT": { en: "ACCOUNT INSIGHT", hi: "ACCOUNT INSIGHT" },
  "Back to tasks": { en: "Back to tasks", hi: "Tasks par wapas jaayein" },
  "Nothing needs attention": { en: "Nothing needs attention", hi: "Kuch bhi dhyaan dene layak nahi hai" },
  "One or more items need attention": { en: "One or more items need attention", hi: "Ek ya zyada items par dhyaan dena hai" },
  "ACCOUNT INSIGHTS": { en: "ACCOUNT INSIGHTS", hi: "ACCOUNT INSIGHTS" },
  "Or choose a question": { en: "Or choose a question", hi: "Ya ek sawaal chunein" },
  "Read-only, no approval needed": { en: "Read-only, no approval needed", hi: "Sirf padhne ke liye, approval ki zaroorat nahi" },
  "Read-only": { en: "Read-only", hi: "Sirf padhne ke liye" },
  "ACCOUNT ACTIONS": { en: "ACCOUNT ACTIONS", hi: "ACCOUNT ACTIONS" },
  "Prepare a request": { en: "Prepare a request", hi: "Ek request taiyaar karein" },
  "Every action pauses for approval": { en: "Every action pauses for approval", hi: "Har action approval ke liye ruk jaata hai" },
  "This agent gives guidance, not a decision. EPFO filing rules and verification still apply.": { en: "This agent gives guidance, not a decision. EPFO filing rules and verification still apply.", hi: "Yeh agent guidance deta hai, decision nahi. EPFO ke filing rules aur verification abhi bhi lagu hote hain." },
  Ready: { en: "Ready", hi: "Ready hai" },
  "Action needed": { en: "Action needed", hi: "Action chahiye" },
  "Ask in your own words": { en: "Ask in your own words", hi: "Apne shabdon mein poochein" },
  "Ask about ECR, contributions, or compliance…": { en: "Ask about ECR, contributions, or compliance…", hi: "ECR, contributions, ya compliance ke baare mein poochein…" },
  Ask: { en: "Ask", hi: "Poochein" },
  "Example questions": { en: "Example questions", hi: "Udaharan sawaal" },
  "Try asking": { en: "Try asking", hi: "Ye poochh kar dekhein" },
  "Did I file this month's ECR for everyone?": { en: "Did I file this month's ECR for everyone?", hi: "Kya maine is mahine sabke liye ECR file kar diya?" },
  "When is my contribution payment due?": { en: "When is my contribution payment due?", hi: "Mera contribution payment kab due hai?" },
  "How many employees still need KYC approval?": { en: "How many employees still need KYC approval?", hi: "Kitne employees ko abhi bhi KYC approval chahiye?" },
  "What's pending before I'm fully compliant?": { en: "What's pending before I'm fully compliant?", hi: "Poori tarah compliant hone se pehle kya pending hai?" },
  "Is my digital signature still valid?": { en: "Is my digital signature still valid?", hi: "Kya mera digital signature abhi bhi valid hai?" },
  "Couldn't reach the intent service. Confirm OPENAI_API_KEY is set and try again.": { en: "Couldn't reach the intent service. Confirm OPENAI_API_KEY is set and try again.", hi: "Intent service tak nahi pahunch paaye. OPENAI_API_KEY set hai ya nahi confirm karein aur dobara try karein." },
  "Understands your question with AI, then answers only from this account's real filing status and EPFO's own rules.": { en: "Understands your question with AI, then answers only from this account's real filing status and EPFO's own rules.", hi: "Aapke sawaal ko AI se samajhta hai, phir jawaab sirf is account ki asli filing status aur EPFO ke apne rules se deta hai." },
  "Check this month's ECR filing": { en: "Check this month's ECR filing", hi: "Is mahine ki ECR filing check karein" },
  "Check the contribution due date": { en: "Check the contribution due date", hi: "Contribution ki due date check karein" },
  "Check compliance readiness": { en: "Check compliance readiness", hi: "Compliance readiness check karein" },
  "KYC approvals": { en: "KYC approvals", hi: "KYC approvals" },
  "Exit confirmations": { en: "Exit confirmations", hi: "Exit confirmations" },
  "Digital signature": { en: "Digital signature", hi: "Digital signature" },
};

const STORAGE_KEY = "epfo.lang";

const romanized: Partial<Record<Lang, Record<string, string>>> = {
  hi: { Home: "Ghar", Claims: "Daave", "Service history": "Seva itihaas", "Profile details": "Profile vivaran", "File a Claim": "Daava darj karein", "Claim status": "Daave ki sthiti", "Need help?": "Madad chahiye?", "Sign in to EPFO": "EPFO mein sign in karein", "Your retirement account": "Aapka retirement account", "Good afternoon, Rahul": "Namaste, Rahul" },
  bn: { Home: "Bari", Claims: "Dabi", "Service history": "Seva itihas", "Profile details": "Profile bishad", "File a Claim": "Dabi dakhil korun", "Claim status": "Dabir sthiti", "Need help?": "Sahayata lagbe?", "Sign in to EPFO": "EPFO-te sign in korun", "Your retirement account": "Apnar obosor account", "Good afternoon, Rahul": "Nomoskar, Rahul" },
  mr: { Home: "Mukhya prushtha", Claims: "Daave", "Service history": "Seva itihas", "Profile details": "Profile tapshil", "File a Claim": "Dava dakhla kara", "Claim status": "Davyachi sthiti", "Need help?": "Madat havi?", "Sign in to EPFO": "EPFO madhye sign in kara", "Your retirement account": "Tumche nivrutti khate", "Good afternoon, Rahul": "Namaskar, Rahul" },
  te: { Home: "Mukhya peji", Claims: "Kleimlu", "Service history": "Seva charitra", "Profile details": "Profile vivaralu", "File a Claim": "Kleim dakhala cheyandi", "Claim status": "Kleim sthiti", "Need help?": "Sahayam kavala?", "Sign in to EPFO": "EPFO lo sign in cheyandi", "Your retirement account": "Mee retirement account", "Good afternoon, Rahul": "Namaskaram, Rahul" },
  ta: { Home: "Mugappu", Claims: "Koorikkaigal", "Service history": "Sevai varalaru", "Profile details": "Profile vivarangal", "File a Claim": "Koorikkaiyai samarpikkavum", "Claim status": "Koorikkai nilai", "Need help?": "Udhavi venduma?", "Sign in to EPFO": "EPFO-il sign in seyyavum", "Your retirement account": "Ungal retirement account", "Good afternoon, Rahul": "Vanakkam, Rahul" },
  gu: { Home: "Mukhya", Claims: "Daavao", "Service history": "Seva itihas", "Profile details": "Profile vigato", "File a Claim": "Daavo dakhla karo", "Claim status": "Daavani sthiti", "Need help?": "Madad joie?", "Sign in to EPFO": "EPFO ma sign in karo", "Your retirement account": "Tamaru retirement account", "Good afternoon, Rahul": "Namaste, Rahul" },
  kn: { Home: "Mukhya puta", Claims: "Kleimgalu", "Service history": "Seva charitre", "Profile details": "Profile vivaragaLu", "File a Claim": "Kleim sallisi", "Claim status": "Kleim sthiti", "Need help?": "Sahaya beke?", "Sign in to EPFO": "EPFO ge sign in maadi", "Your retirement account": "Nimma retirement account", "Good afternoon, Rahul": "Namaskara, Rahul" },
  ml: { Home: "Home", Claims: "Claimukal", "Service history": "Sevana charithram", "Profile details": "Profile vivarangal", "File a Claim": "Claim samarpikkuka", "Claim status": "Claim nila", "Need help?": "Sahayam venamo?", "Sign in to EPFO": "EPFO-il sign in cheyyuka", "Your retirement account": "Ningalude retirement account", "Good afternoon, Rahul": "Namaskaram, Rahul" },
  pa: { Home: "Ghar", Claims: "Daave", "Service history": "Seva itihas", "Profile details": "Profile verve", "File a Claim": "Daava darj karo", "Claim status": "Daave di sthiti", "Need help?": "Madad chahidi?", "Sign in to EPFO": "EPFO vich sign in karo", "Your retirement account": "Tuhada retirement account", "Good afternoon, Rahul": "Sat sri akaal, Rahul" },
  or: { Home: "Mukhya prustha", Claims: "Dabi", "Service history": "Seva itihasa", "Profile details": "Profile bibarana", "File a Claim": "Dabi dakhala karantu", "Claim status": "Dabi sthiti", "Need help?": "Sahayata darkar?", "Sign in to EPFO": "EPFO re sign in karantu", "Your retirement account": "Apankara retirement account", "Good afternoon, Rahul": "Namaskar, Rahul" },
};

type LanguageContextValue = {
  lang: Lang;
  setLang: (lang: Lang) => void;
  toggle: () => void;
  t: (text: string) => string;
  tpl: (key: string, params?: Record<string, string>) => string;
};

function subscribeLanguage(onStoreChange: () => void) {
  window.addEventListener("storage", onStoreChange);
  return () => window.removeEventListener("storage", onStoreChange);
}

function readLanguage(): Lang {
  const stored = window.localStorage.getItem(STORAGE_KEY);
  return languages.some(({ id }) => id === stored) ? stored as Lang : "en";
}

function readLanguageServer(): Lang {
  return "en";
}

function writeLanguage(lang: Lang) {
  window.localStorage.setItem(STORAGE_KEY, lang);
  window.dispatchEvent(new Event("storage"));
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const lang = useSyncExternalStore(subscribeLanguage, readLanguage, readLanguageServer);

  const setLang = useCallback((next: Lang) => writeLanguage(next), []);
  const toggle = useCallback(() => writeLanguage(lang === "en" ? "hi" : "en"), [lang]);

  // For "hi" specifically, dict[text].hi carries an authored Romanized-Hindi translation for many keys beyond the small shared romanized[] set — without this fallback those keys silently rendered in English.
  const t = useCallback((text: string) => lang === "en" ? dict[text]?.en ?? text : romanized[lang]?.[text] ?? (lang === "hi" ? dict[text]?.hi : undefined) ?? dict[text]?.en ?? text, [lang]);

  const tpl = useCallback(
    (key: string, params?: Record<string, string>) => {
      let out = lang === "en" ? dict[key]?.en ?? key : romanized[lang]?.[key] ?? (lang === "hi" ? dict[key]?.hi : undefined) ?? dict[key]?.en ?? key;
      if (params) {
        for (const [paramKey, value] of Object.entries(params)) {
          out = out.replaceAll(`{${paramKey}}`, value);
        }
      }
      return out;
    },
    [lang],
  );

  return <LanguageContext.Provider value={{ lang, setLang, toggle, t, tpl }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
