"use client";

import { useMemo, useState } from "react";
import { LanguageProvider, useLanguage } from "./language";

type Context = { id: string; name: string; role: string; meta: string; type: "member" | "employer"; accent: string };
const contexts: Context[] = [
  { id: "member", name: "My PF", role: "Member", meta: "UAN •••• 1234", type: "member", accent: "PF" },
  { id: "abc", name: "ABC Pvt Ltd", role: "CA", meta: "All extensions", type: "employer", accent: "AB" },
  { id: "xyz", name: "XYZ Consulting", role: "Authorized Signatory", meta: "Head office · 000", type: "employer", accent: "XY" },
];
const navByType = {
  member: ["Overview", "My employment", "Passbook", "Claims", "KYC & profile", "Nomination", "Documents"],
  employer: ["Overview", "Employees", "ECR & contributions", "Payments", "Compliance", "Reports", "Users & access"],
};

function Icon({ name, size = 20 }: { name: string; size?: number }) {
  const paths: Record<string, React.ReactNode> = {
    home: <><path d="M3 10.8 12 3l9 7.8"/><path d="M5 9.8V21h14V9.8M9 21v-7h6v7"/></>,
    briefcase: <><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M3 12h18M10 12v2h4v-2"/></>,
    book: <><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2Z"/></>,
    file: <><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6M8 13h8M8 17h5"/></>,
    user: <><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,
    shield: <><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10"/><path d="m9 12 2 2 4-4"/></>,
    bell: <><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></>,
    search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, chevron: <path d="m8 10 4 4 4-4"/>,
    arrow: <><path d="M5 12h14M13 6l6 6-6 6"/></>, claim: <><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M7 9h10M7 13h5"/></>,
    building: <><path d="M3 21h18M6 21V5l6-3 6 3v16M9 9h.01M15 9h.01M9 13h.01M15 13h.01M10 21v-4h4v4"/></>,
    payment: <><rect x="2" y="5" width="20" height="14" rx="2"/><path d="M2 10h20M6 15h2"/></>,
    users: <><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></>,
    menu: <><path d="M4 7h16M4 12h16M4 17h16"/></>, close: <><path d="m6 6 12 12M18 6 6 18"/></>,
  };
  return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name] ?? paths.home}</svg>;
}

function LangSwitch() {
  const { lang, setLang } = useLanguage();
  return <div className="lang-switch" role="group" aria-label="Language">
    <button type="button" className={lang === "en" ? "active" : ""} onClick={() => setLang("en")} aria-label="English">EN</button>
    <button type="button" className={lang === "hi" ? "active" : ""} onClick={() => setLang("hi")} aria-label="Hindi">हिं</button>
  </div>;
}

export default function Home() {
  return <LanguageProvider><Portal /></LanguageProvider>;
}

function Portal() {
  const { t, tpl } = useLanguage();
  const [activeId, setActiveId] = useState("member"); const [switchOpen, setSwitchOpen] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); const [activeNav, setActiveNav] = useState("Overview");
  const active = useMemo(() => contexts.find((item) => item.id === activeId) ?? contexts[0], [activeId]); const isMember = active.type === "member";
  const chooseContext = (context: Context) => { setActiveId(context.id); setActiveNav("Overview"); setSwitchOpen(false); };
  return <main className="app-shell">
    <header className="topbar"><div className="brand"><button className="mobile-menu" onClick={() => setMobileOpen(!mobileOpen)} aria-label={t("Open navigation")}><Icon name="menu"/></button><div className="national-mark">अ</div><div><div className="brand-title">EPFO</div><div className="brand-sub">Employees&apos; Provident Fund Organisation</div></div></div><div className="topbar-actions"><label className="search"><Icon name="search" size={18}/><input aria-label={t("Search EPFO services")} placeholder={t("Search services")}/></label><button className="icon-button" aria-label={t("Notifications")}><Icon name="bell"/><span className="notification-dot"/></button><LangSwitch/><button className="profile-button"><span className="avatar">RP</span><span className="profile-copy"><strong>Rahul Patil</strong><small>{t("Verified account")}</small></span><Icon name="chevron" size={16}/></button></div></header>
    <aside className={`sidebar ${mobileOpen ? "sidebar-open" : ""}`}><button className="mobile-close" onClick={() => setMobileOpen(false)} aria-label={t("Close navigation")}><Icon name="close"/></button><div className="context-label">{t("Currently acting as")}</div><button className="context-card" onClick={() => setSwitchOpen(true)}><span className="context-icon">{active.accent}</span><span className="context-copy"><strong>{t(active.name)}</strong><small>{t(active.role)}</small></span><Icon name="chevron" size={16}/></button><nav className="nav-list" aria-label={t("Main navigation")}>{navByType[active.type].map((item,index)=>{const icons=isMember?["home","briefcase","book","claim","user","shield","file"]:["home","users","file","payment","shield","book","user"];return <button key={item} className={activeNav===item?"active":""} onClick={()=>{setActiveNav(item);setMobileOpen(false)}}><Icon name={icons[index]}/><span>{t(item)}</span>{activeNav===item&&<i/>}</button>})}</nav><div className="sidebar-help"><span className="help-icon">?</span><div><strong>{t("Need help?")}</strong><small>{t("Guides and support")}</small></div><Icon name="arrow" size={16}/></div></aside>
    <section className="content"><div className="context-strip"><span className="verified-pill"><Icon name="shield" size={15}/> Aadhaar verified</span><button onClick={()=>setSwitchOpen(true)}>{t("Acting as")}: <strong>{t(active.name)} · {t(active.role)}</strong><Icon name="chevron" size={15}/></button></div><div className="page-head"><div><p className="eyebrow">{t("MONDAY, 24 AUGUST")}</p><h1>{t("Good afternoon, Rahul")}</h1><p>{isMember?t("Here’s a clear view of your provident fund."):tpl("Here’s what needs attention at {name}.",{name:t(active.name)})}</p></div><button className="outline-button"><Icon name="file" size={17}/>{isMember?t("Download statement"):t("Download report")}</button></div>
      {activeNav!=="Overview"?<section className="placeholder-view"><div className="placeholder-icon"><Icon name={isMember?"book":"building"} size={26}/></div><p className="eyebrow">{t(active.name)}</p><h2>{t(activeNav)}</h2><p>{tpl("This workspace is ready for the {item} journey. Your active role and scope remain visible while you work.",{item:t(activeNav).toLowerCase()})}</p><button className="primary-button" onClick={()=>setActiveNav("Overview")}>{t("Return to overview")}</button></section>:isMember?<MemberDashboard/>:<EmployerDashboard context={active}/>}</section>
    {switchOpen&&<div className="modal-backdrop" onMouseDown={()=>setSwitchOpen(false)}><section className="context-modal" role="dialog" aria-modal="true" aria-labelledby="switch-title" onMouseDown={(e)=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">EPFO PROFILES</p><h2 id="switch-title">{t("Switch context")}</h2><p>{t("Choose who you want to act as. You won’t need to sign in again.")}</p></div><button onClick={()=>setSwitchOpen(false)} aria-label={t("Close")}><Icon name="close"/></button></div><div className="context-options">{contexts.map(context=><button key={context.id} onClick={()=>chooseContext(context)} className={context.id===active.id?"selected":""}><span className="context-icon large">{context.accent}</span><span><strong>{t(context.name)}</strong><small>{t(context.role)} · {t(context.meta)}</small></span>{context.id===active.id?<span className="current-tag">{t("Current")}</span>:<Icon name="arrow" size={18}/>}</button>)}</div><div className="modal-note"><Icon name="shield" size={18}/><span>{t("Sensitive actions may require an OTP or e-Sign confirmation.")}</span></div></section></div>}
  </main>;
}

function MemberDashboard(){const {t}=useLanguage();return <><section className="balance-card"><div><p>{t("Your total PF balance")} <span className="info">i</span></p><h2>₹4,52,340<span>.00</span></h2><div className="balance-meta"><span><i className="up">↑</i> {t("₹8,430 contribution in August")}</span><span>{t("Last updated 18 Aug 2026")}</span></div></div><div className="balance-visual"><div className="donut"><div><strong>72%</strong><small>{t("Employee share")}</small></div></div><div className="legend"><span><i className="employee"/>{t("Employee share")} <strong>₹3,25,685</strong></span><span><i className="employer"/>{t("Employer share")} <strong>₹1,26,655</strong></span></div></div></section><section className="quick-section"><div className="section-heading"><h2>{t("Quick actions")}</h2><span>{t("Most-used services")}</span></div><div className="quick-grid"><Action icon="book" title={t("View passbook")} text={t("See every contribution")}/><Action icon="claim" title={t("Withdraw / claim PF")} text={t("Start or track a claim")}/><Action icon="user" title={t("Update KYC")} text={t("Keep details verified")}/><Action icon="shield" title={t("Add nomination")} text={t("Protect your family")}/></div></section><section className="dashboard-grid"><article className="panel employment-panel"><div className="panel-head"><div><p className="eyebrow">{t("MY EMPLOYMENT")}</p><h2>{t("3 linked employers")}</h2></div><button>{t("View all")} <Icon name="arrow" size={15}/></button></div><Timeline logo="IN" company="Infosys Limited" detail={t("Current employment")} sub="Member ID •••• 7821" status={t("Active")} tone="blue"/><Timeline logo="TC" company="Techcore Systems" detail="Apr 2021 – Jun 2023" sub={t("PF transferred successfully")} status={t("Transferred")} tone="amber"/></article><article className="panel claim-panel"><div className="panel-head"><div><p className="eyebrow">{t("LATEST CLAIM")}</p><h2>{t("Claim progress")}</h2></div><span className="status processing">{t("In review")}</span></div><strong className="claim-amount">₹35,000</strong><p className="claim-type">{t("Advance claim · Submitted 12 Aug")}</p><div className="progress-steps"><i className="complete"/><i className="complete"/><i className="active"/><i/></div><div className="progress-labels"><span>{t("Submitted")}</span><span>{t("Verification")}</span><span>{t("Review")}</span><span>{t("Paid")}</span></div><div className="claim-note"><Icon name="shield" size={18}/><span>{t("Your employer verification is complete. EPFO review is in progress.")}</span></div></article></section></>}
function EmployerDashboard({context}:{context:Context}){const {t}=useLanguage();return <><section className="stat-grid"><Stat label={t("Active employees")} value="4,823" note={t("+42 this month")} tone="blue" icon="users"/><Stat label={t("ECR status")} value={t("Submitted")} note="August 2026" tone="green" icon="file"/><Stat label={t("Contribution")} value="₹2.4 Cr" note={t("Payment due 15 Sep")} tone="amber" icon="payment"/><Stat label={t("Compliance")} value={t("Good")} note={t("No action required")} tone="green" icon="shield"/></section><section className="dashboard-grid employer-grid"><article className="panel"><div className="panel-head"><div><p className="eyebrow">AUGUST ECR</p><h2>{t("Contribution filing")}</h2></div><span className="status active">{t("Submitted")}</span></div><div className="filing-row"><div><span>{t("Employees included")}</span><strong>4,801</strong></div><div><span>{t("Gross wages")}</span><strong>₹18.6 Cr</strong></div><div><span>TRRN</span><strong>1252608001842</strong></div></div><div className="claim-note"><Icon name="shield" size={18}/><span>{t("Submission signed by the Authorized Signatory on 18 August.")}</span></div></article><article className="panel"><div className="panel-head"><div><p className="eyebrow">{t("ATTENTION")}</p><h2>{t("Tasks to complete")}</h2></div><button>{t("View all")} <Icon name="arrow" size={15}/></button></div><Task tone="amber" title="22 KYC requests" text={t("Awaiting employer approval")}/><Task tone="blue" title="7 employee exits" text={t("Last working day to confirm")}/></article></section><section className="panel activity-panel"><div className="panel-head"><div><p className="eyebrow">{t("RECENT ACTIVITY")}</p><h2>{t(context.name)}</h2></div><button>{t("Download report")} <Icon name="arrow" size={15}/></button></div><div className="activity-table"><div><span><i className="activity-icon green"><Icon name="file" size={16}/></i><b>{t("August ECR submitted")}</b></span><span>18 Aug 2026</span><span>Rahul Patil</span><span className="status done">{t("Complete")}</span></div><div><span><i className="activity-icon blue"><Icon name="payment" size={16}/></i><b>{t("July payment reconciled")}</b></span><span>14 Aug 2026</span><span>System</span><span className="status done">{t("Matched")}</span></div></div></section></>}
function Action({icon,title,text}:{icon:string;title:string;text:string}){return <button className="action-card"><span><Icon name={icon}/></span><div><strong>{title}</strong><small>{text}</small></div><Icon name="arrow" size={17}/></button>}
function Timeline({logo,company,detail,sub,status,tone}:{logo:string;company:string;detail:string;sub:string;status:string;tone:string}){return <div className="timeline-item"><span className={`company-logo ${tone}`}>{logo}</span><div><strong>{company}</strong><p>{detail}</p><small>{sub}</small></div><span className="status done">{status}</span></div>}
function Stat({label,value,note,tone,icon}:{label:string;value:string;note:string;tone:string;icon:string}){return <article className="stat-card"><div className={`stat-icon ${tone}`}><Icon name={icon}/></div><p>{label}</p><h2>{value}</h2><span className={tone}>{note}</span></article>}
function Task({tone,title,text}:{tone:string;title:string;text:string}){return <div className="task-row"><span className={`task-dot ${tone}`}/><div><strong>{title}</strong><p>{text}</p></div><Icon name="arrow" size={17}/></div>}