"use client";

import { useState } from "react";

type Profile = { id: string; kind: string; name: string; identifier: string; role?: string; description: string; action: string };
type Service = { name: string; description: string };
type ServiceGroup = { title: string; services: Service[] };

const memberServices: ServiceGroup[] = [
  { title: "My account", services: [{ name: "Profile", description: "Your personal details and contact information." }, { name: "UAN", description: "View your Universal Account Number." }, { name: "My employment", description: "See current and previous employment." }, { name: "Profile update requests", description: "Track requested changes to your profile." }, { name: "Documents", description: "Access letters and submitted documents." }] },
  { title: "My PF", services: [{ name: "PF balance", description: "See your available PF balance." }, { name: "Passbook", description: "Review your contribution passbook." }, { name: "Contributions", description: "See monthly deposits from employers." }, { name: "KYC", description: "Review and update verified KYC details." }, { name: "Nomination", description: "Add or update your nominee." }] },
  { title: "Claims and pension", services: [{ name: "Withdraw / Claim PF", description: "Start a PF withdrawal or claim." }, { name: "Claim tracking", description: "Check the status of an existing claim." }, { name: "Transfer", description: "Move PF balance from a previous employer." }, { name: "Pension information", description: "View pension-related information." }, { name: "Notifications", description: "See account updates and reminders." }] },
];

const establishmentServices: ServiceGroup[] = [
  { title: "Organization", services: [{ name: "Establishment profile", description: "Manage establishment details." }, { name: "Registration and coverage", description: "Review coverage and registration information." }, { name: "Contact information", description: "Update official contact details." }, { name: "Branches", description: "Manage extension codes and branch access." }, { name: "DSC / e-Sign", description: "Manage signing credentials." }, { name: "Authorized signatories", description: "View or manage authorized signatories." }] },
  { title: "Employees", services: [{ name: "Employee management", description: "Manage employee records." }, { name: "Joining and leaving", description: "Record employee joiners and leavers." }, { name: "UAN and member information", description: "Review linked UAN and member details." }, { name: "KYC operations", description: "Handle employee KYC-related operations." }] },
  { title: "Contributions", services: [{ name: "ECR", description: "Prepare and submit UAN-based ECR." }, { name: "ECR validation", description: "Validate contribution return data." }, { name: "Contribution calculation", description: "Review contribution calculations." }, { name: "Challans", description: "View TRRN challans." }, { name: "Payments", description: "Review and make contribution payments." }, { name: "Payment reconciliation", description: "Reconcile payment records." }] },
  { title: "Compliance", services: [{ name: "Compliance status", description: "Review establishment compliance." }, { name: "Notices", description: "View EPFO notices." }, { name: "Correspondence", description: "Manage official correspondence." }, { name: "Reports", description: "Generate establishment reports." }, { name: "Employer claim actions", description: "Review employer-side claim actions." }] },
  { title: "Contractors", services: [{ name: "Contractor management", description: "Manage contractor relationships." }, { name: "Contracts and work orders", description: "Record contract and work-order information." }, { name: "Contract-worker mapping", description: "Map workers to contractors." }, { name: "Contractor compliance", description: "Review contractor compliance visibility." }] },
  { title: "Administration", services: [{ name: "Delegated users", description: "Manage people acting for the establishment." }, { name: "Roles", description: "Assign predefined roles." }, { name: "Permissions", description: "Review access by scope and permission." }] },
];

const principalEmployerServices: ServiceGroup[] = [
  { title: "Organization", services: [{ name: "Principal Employer registration", description: "Manage establishment-code or PAN registration." }, { name: "Organization profile", description: "Update organization information." }, { name: "Notifications", description: "Review organization updates." }] },
  { title: "Contractors and workers", services: [{ name: "Contractor management", description: "Add and manage contractors." }, { name: "Contracts and work orders", description: "Record contracts and work orders." }, { name: "Contract-worker mapping", description: "Map workers to contracts." }, { name: "UAN verification", description: "Verify contract-worker UAN details." }] },
  { title: "Compliance", services: [{ name: "Contractor ECR visibility", description: "Review contractor ECR submissions." }, { name: "Contribution and remittance visibility", description: "See remittances against contracts." }, { name: "Contractor compliance", description: "Review contractor compliance status." }, { name: "Compliance dashboard", description: "See contractor compliance in one place." }, { name: "Reports", description: "Generate compliance reports." }] },
];

function Mark({ kind }: { kind: string }) {
  return kind === "Member" ? <svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="8" r="3.25" stroke="currentColor" strokeWidth="1.8" /><path d="M5.5 20c.8-3.4 3-5.1 6.5-5.1s5.7 1.7 6.5 5.1" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" /></svg> : <svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="M4 20h16M6.5 20V7.5L12 4l5.5 3.5V20M9 10.5h.01M15 10.5h.01M9 14h.01M15 14h.01" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /></svg>;
}

function Arrow() { return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><path d="M5 12h13M13 7l5 5-5 5" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" /></svg>; }
function Grid() { return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none"><rect x="4" y="4" width="6" height="6" rx="1" stroke="currentColor" strokeWidth="1.7" /><rect x="14" y="4" width="6" height="6" rx="1" stroke="currentColor" strokeWidth="1.7" /><rect x="4" y="14" width="6" height="6" rx="1" stroke="currentColor" strokeWidth="1.7" /><rect x="14" y="14" width="6" height="6" rx="1" stroke="currentColor" strokeWidth="1.7" /></svg>; }

function ProfileMenu({ profiles, activeProfileId, activate }: { profiles: readonly Profile[]; activeProfileId: string | null; activate: (profileId: string) => void }) {
  const activeProfile = profiles.find((profile) => profile.id === activeProfileId);
  return <details className="profile-menu"><summary><span className="avatar" aria-hidden="true">R</span><span className="profile-menu__identity"><strong>Rahul</strong><small>{activeProfile ? activeProfile.name : "Choose a profile"}</small></span><span className="profile-menu__chevron" aria-hidden="true">⌄</span></summary><div className="profile-popover"><div className="profile-popover__account"><span className="avatar" aria-hidden="true">R</span><span><strong>Rahul</strong><small>Verified EPFO account</small></span></div><p>Your EPFO profiles</p><div className="profile-popover__list">{profiles.map((profile) => <button type="button" key={profile.id} onClick={() => activate(profile.id)}><span className="profile-popover__icon"><Mark kind={profile.kind} /></span><span><strong>{profile.name}</strong><small>{profile.role ?? profile.kind}</small></span>{profile.id === activeProfileId && <b aria-label="Current profile">✓</b>}</button>)}</div><button type="button" className="profile-popover__manage" onClick={() => { const menu = document.querySelector<HTMLDetailsElement>(".profile-menu[open]"); menu?.removeAttribute("open"); }}>Manage profiles</button></div></details>;
}

function servicesFor(kind: string) { return kind === "Member" ? memberServices : kind === "Establishment" ? establishmentServices : principalEmployerServices; }

export default function ProfileChooser({ profiles }: { profiles: readonly Profile[] }) {
  const [activeProfileId, setActiveProfileId] = useState<string | null>(null);
  const [selectedService, setSelectedService] = useState<Service | null>(null);
  const activeProfile = profiles.find((profile) => profile.id === activeProfileId);
  const activate = (profileId: string) => { setActiveProfileId(profileId); setSelectedService(null); };

  if (activeProfile) {
    const groups = servicesFor(activeProfile.kind);
    return <div className="platform-shell">
      <aside className="platform-sidebar"><button className="platform-brand" type="button" onClick={() => setActiveProfileId(null)} aria-label="Choose another EPFO profile"><span className="brand-mark" aria-hidden="true">EP</span><span><strong>EPFO</strong><small>Unified Services</small></span></button><div className="sidebar-section"><p>Your profiles</p>{profiles.map((profile) => <button key={profile.id} className={`profile-nav ${profile.id === activeProfile.id ? "is-active" : ""}`} type="button" onClick={() => activate(profile.id)}><span><Mark kind={profile.kind} /></span><span><strong>{profile.name}</strong><small>{profile.role ?? profile.kind}</small></span></button>)}</div><div className="sidebar-bottom"><button type="button" onClick={() => setActiveProfileId(null)}><Grid /> Switch profile</button><a href="#support">Help and support</a></div></aside>
      <div className="platform-main"><header className="platform-topbar"><div><p>Acting as</p><strong>{activeProfile.name}{activeProfile.role ? ` · ${activeProfile.role}` : ""}</strong></div><div><button type="button" className="topbar-link">English</button><button type="button" className="notification-button" aria-label="Notifications">●</button><ProfileMenu profiles={profiles} activeProfileId={activeProfileId} activate={activate} /></div></header><main className="service-catalogue" id="main-content"><section className="catalogue-intro"><div><p className="eyebrow">{activeProfile.kind}</p><h1>{activeProfile.name}</h1><p>{activeProfile.description}</p></div><button type="button" className="outline-button" onClick={() => setActiveProfileId(null)}>Change profile</button></section>{selectedService && <section className="service-selection" aria-live="polite"><div><p className="eyebrow">Selected service</p><strong>{selectedService.name}</strong><span>{selectedService.description}</span></div><button type="button" onClick={() => setSelectedService(null)}>Close</button></section>}<section className="catalogue-heading"><div><h2>Services</h2><p>Choose a service to continue.</p></div><span>{groups.reduce((total, group) => total + group.services.length, 0)} services available</span></section><div className="service-groups">{groups.map((group) => <section className="service-group" key={group.title} aria-labelledby={`group-${group.title.replaceAll(" ", "-")}`}><h3 id={`group-${group.title.replaceAll(" ", "-")}`}>{group.title}</h3><div className="service-grid">{group.services.map((service) => <button key={service.name} className={`service-card ${selectedService?.name === service.name ? "is-selected" : ""}`} type="button" onClick={() => setSelectedService(service)}><span><strong>{service.name}</strong><small>{service.description}</small></span><Arrow /></button>)}</div></section>)}</div></main><footer id="support" className="platform-footer">EPFO Unified Services · Prototype <a href="mailto:help@example.epfo.gov.in">Contact support</a></footer></div>
    </div>;
  }

  return <div className="service-shell"><header className="service-header"><a className="brand" href="#main-content" aria-label="EPFO home"><span className="brand-mark" aria-hidden="true">EP</span><span><strong>EPFO</strong><small>Unified Services</small></span></a><nav className="utility-nav" aria-label="Utility navigation"><a href="#support">Help</a><button type="button" className="language-button" aria-label="Language: English">English</button><ProfileMenu profiles={profiles} activeProfileId={null} activate={activate} /></nav></header><main id="main-content" className="service-main"><section className="profile-chooser" aria-labelledby="profiles-title"><div className="profile-workspace"><div><div className="intro-copy profile-intro"><p className="eyebrow">Your EPFO account</p><h1 id="profiles-title">Everything EPFO, under one sign-in.</h1><p>Good morning, Rahul. Choose what you want to do today; your profiles remain available from the account menu above.</p><div className="profile-intro__note"><span>3</span><p>profiles linked to your verified identity</p></div></div><div className="profile-list" aria-label="Available EPFO profiles">{profiles.map((profile) => <button className={`profile-card profile-card--${profile.id}`} type="button" key={profile.id} onClick={() => activate(profile.id)}><span className="profile-card__icon"><Mark kind={profile.kind} /></span><span className="profile-card__content"><span className="profile-card__kind">{profile.kind}</span><span className="profile-card__name">{profile.name}</span><span className="profile-card__identifier">{profile.identifier}</span>{profile.role && <span className="profile-card__role">{profile.role}</span>}<span className="profile-card__description">{profile.description}</span><span className="profile-card__action">{profile.action}<Arrow /></span></span></button>)}</div></div><aside className="desktop-guide"><p className="eyebrow">One account</p><h2>Switch contexts without signing in again.</h2><p>Member, establishment, and Principal Employer services are kept separate, so you always know who you are acting as.</p><div className="desktop-guide__tip"><span>Tip</span><p>Use Rahul’s account menu in the top-right to switch profiles from anywhere.</p></div></aside></div></section></main><footer id="support" className="service-footer"><span>EPFO Unified Services · Prototype</span><span>Need help? <a href="mailto:help@example.epfo.gov.in">Contact support</a></span></footer></div>;
}
